### ISSUE TITLE
Application Crashing / Flashing

### ISSUE THREAD

**Issue by Solopants** [ChrisAnd1998/FalconX-Center-Taskbar#100]
FalconX is repeatedly crashing and restarting itself. This rarely impacts the actual function of the program, to centre taskbar icons, but it does create an annoying flashing window pop-up quite frequently.

Love the program still. Just wanted to report this issue so that it could perhaps be resolved.

I was unable to attach the GIF I recorded due to the filesize limit on attachments.

See GIF recording [here](https://my.pcloud.com/publink/show?code=XZpcvmkZsqfi7gDLJPQbXb7fbp1KgVJgfq9X). This little 'flash' happens quite a lot when you are using your computer throughout the day. I can also confirm the issue happens on other devices as I use the program at work and on my laptop.

Feel free to ask for additional information. I may take a short while to respond but I will respond as soon as I see a notification.

Cheers!

**Comment by ChrisAnd1998** [comment]
I am working on it. Does this testing build already fix it for you?
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v1.zip

**Comment by Solopants** [comment]
Hi Chris,

I have just set it running. Not noticed the flashing yet (it usually happens quite frequently when opening programs, especially when the desktop is otherwise empty) so I will give it a whirl for the rest of the day and post back with anything I notice.

Cheers.

**Comment by ChrisAnd1998** [comment]
Thanks! i'll wait for your response :)

**Comment by Solopants** [comment]
Okay first thing I have noticed is: on an empty desktop (no programs open so nothing on taskbar) a similar issue is happening whereby the icon is flashing briefly on the taskbar then disappearing. Definitely less of an issue than before.

Recording [here](https://my.pcloud.com/publink/show?code=XZyRimkZ8kDOwJx9RqR6HAorgNpMCXL5LtCy).

Hope this helps.

**Comment by Solopants** [comment]
Issue doesn't appear to be happening when windows are open at all. I'll keep my eyes peeled.

**Comment by Gold-Flake** [comment]
I am having the same problem as above. The application repeatedly restarts itself when on my empty desktop with no programs open.

**Comment by ChrisAnd1998** [comment]
Should be fixed now in 1.3.4.0!
