### ISSUE TITLE
icons flying out when taskbar is leftside on 2nd monitor

### ISSUE THREAD

**Issue by waltereikrem** [ChrisAnd1998/FalconX-Center-Taskbar#101]
when i enable 'center on multiple monitors' my icons just fall down and dissapear. only on the 2nd monitor tho. 

under is a long screensnip of the taskbars.
![image](https://user-images.githubusercontent.com/43746219/70382601-0b46d380-195f-11ea-8bad-267fec837615.png)

**Comment by ChrisAnd1998** [comment]
Hmm, on what version are you?
"Center on multiple monitors" 
Is an option from the older versions of FalconX.

1.3.3.0 is currently the latest ;)
