### ISSUE TITLE
Crashing and restarting when gaming

### ISSUE THREAD

**Issue by TheCaptainBrock** [ChrisAnd1998/FalconX-Center-Taskbar#102]
So since the day before yesterday I noticed my GTA minimizing.
Turns out FalconX is constantly restarting itself in the background when the game is running.

**Comment by ChrisAnd1998** [comment]
There have been some issues last update.

Does this testing build fix the issue?
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v2.zip

**Comment by TheCaptainBrock** [comment]
No it didn't fix my issue.

**Comment by ChrisAnd1998** [comment]
What about?
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v5.zip

**Comment by TheCaptainBrock** [comment]
Sadly no, this also didnt fix my issue. i tried to record my steps but since everything crashes and minimizes it didnt capture the problem.

**Comment by ChrisAnd1998** [comment]
Weird :( did this also happen on 1.3.2.0?

**Comment by TheCaptainBrock** [comment]
I dont think so. at the start of this week everything worked fine :)

**Comment by ChrisAnd1998** [comment]
I have rolled back 1.3.2.0 and added 
* Fixed taskbar appearing blue when using "transparant" Taskbar Style

Making it 1.3.4.0

**Comment by TheCaptainBrock** [comment]
Where can i download that? MStore doesnt see 1.3.4 yet :)

**Comment by ChrisAnd1998** [comment]
I have submitted the update but, it can take up to 3 business days at max for the update to be published. In my experience it will be around tommorow evening.

You can also get it from my website
https://chrisandriessen.nl/

But i suggest waiting for the store version to arrive to avoid possible conflicts.

**Comment by TheCaptainBrock** [comment]
Oke top, bedankt voor je antwoord!
