### ISSUE TITLE
Re-add easings cheat sheet

### ISSUE THREAD

**Issue by swsegdan** [ChrisAnd1998/FalconX-Center-Taskbar#103]
Since it's not in the app anymore, maybe add the URL to the readme? (i.e. https://easings.net/en )

**Comment by Martin5001** [comment]
Showing video preview in a similar way Windows 10 does in settings may work well.

**Comment by Martin5001** [comment]
(Another idea related to this but I opened a new issue for it as it is alread implemented now: #112)
