### ISSUE TITLE
Incompatible with other software

### ISSUE THREAD

**Issue by Gugufly** [ChrisAnd1998/FalconX-Center-Taskbar#104]
FalconX will cause a tool that displays the network speed in the toolbar to be invalid. You cannot change its position as the tray icon increases or decreases.It is called NetSpeedMonitor. Can you fix it？Or can falconx be add the function of displaying network speed? Thanks！

**Comment by Gugufly** [comment]
If this request is unreasonable, please forgive me...

**Comment by ChrisAnd1998** [comment]
Thanks for notifying the issue i will definitely look into this when i have more time. I will close this one because, this has already been reported couple days ago and to avoid duplicates ;) #96
