### ISSUE TITLE
A small issue

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/FalconX-Center-Taskbar#107]
Now on Windows 10, we start to use the light theme, but the right-click menu of tray icon is still black, which is a little inconsistent with the system. So, in fact, I don't know how to set this up properly. It's a bit of a fuss to use a function that matches the system theme alone.

**Comment by ChrisAnd1998** [comment]
Hi,

Thanks for requesting this feature / ui modification. This is something i wanted to do at a later version of FalconX ;)

I only have to close this one to avoid duplicates #68
