### ISSUE TITLE
Reboot after enabling Run at StartUp causes program crash restart cycle

### ISSUE THREAD

**Issue by ThimbleFire** [ChrisAnd1998/FalconX-Center-Taskbar#109]
![](https://i.imgur.com/oB1D3Gu.png)

**Comment by swsegdan** [comment]
There is already a new version available that fixes this. Also, double check if there already exists a ticket for any issue before you post 'cause this is probably the 5th thread on the same thing.

**Comment by ChrisAnd1998** [comment]
@swsegdan Thanks for the heads up :)
