### ISSUE TITLE
Icons continuously move in Win10 125% scaling 

### ISSUE THREAD

**Issue by TofuNinja5** [ChrisAnd1998/FalconX-Center-Taskbar#111]
Hi Chris,
I remember having this issue before, and I also remember this being fixed just a version or two ago. I bought a new laptop this weekend and unfortunately, I'm seeing the same twitchiness in my icons again. I am again on 125% scaling on Win10. All settings are on default, any advice what I should do?

**Comment by TofuNinja5** [comment]
For now, switching to a custom scaling of 120% fixes the issue.

**Comment by ChrisAnd1998** [comment]
I am currently working on a proper fix for this issue. This testing build may fix this.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.5.0_v1.zip

I have to close this issue because, there already is an other issue open with the same issue.
