### ISSUE TITLE
/UI design/ Easings cheatsheet placement

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#112]
Because the easings cheatsheet is an external web resource, I think using a link instead of a button would better communicate that as buttons usually trigger actions _inside_ the app. Also the cheatsheet is related to the animation easing select box in Animation options, so it might look good to place the link next to this selection list.

Example:
![falconx](https://user-images.githubusercontent.com/35201200/70852857-88fe6800-1ea6-11ea-896f-c1531afabf10.png)

**Comment by Cabola** [comment]
Nice idea, could be done sometime when there's nothing better to do.
