### ISSUE TITLE
Gui bugs on 125% scaled screen

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/FalconX-Center-Taskbar#114]
![image](https://user-images.githubusercontent.com/48860358/70862871-d947f980-1f7c-11ea-9c63-ca6edd3905a9.png)
version: 1.3.5.0
There are some problems with font display, and the interface is smaller. 1.3.3.0 is normal. (1.3.4.0 I didn't update it. I don't know if there is this problem.)

**Comment by ChrisAnd1998** [comment]
Yes, i have to find a fix for this. This is happens due to a fix for another bigger bug.

**Comment by ChrisAnd1998** [comment]
I have now seperated the settings window from FalconX in update 1.3.6.0.
So now the settings window will be a little blurry but, accessible again.
I may rewrite the settings window in a different language or WPF.

**Comment by fxzxmicah** [comment]
@ChrisAnd1998 thanks. Does the uwp version have the same experience as the Win32 version? I can buy to sponsor you.

**Comment by ChrisAnd1998** [comment]
For now the experience is exactly the same except that the store version has auto updates.
Would be nice if you want, to support the project :)
