### ISSUE TITLE
Really small typo - "start" should be "Start"

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#115]
Hi,
it looks much better now when the titles are not all in capital letters, thanks for changing this.
But I noticed a small mistake came along the way - The "Center between start, search etc...and tray" there the "start" should be with capitals like "Start" because it is the name of the Start menu in Windows so it is capitalized. But that´s just a really small issue. :)

**Comment by ChrisAnd1998** [comment]
Thanks! I will change it.
