### ISSUE TITLE
Taskbar doesn't hide reliably

### ISSUE THREAD

**Issue by Intoxcity** [ChrisAnd1998/FalconX-Center-Taskbar#122]
I have auto-hide and most often than not it won't hide. Especially when a window is in full screen. So about 80% it stays on the screen. I have dual monitors ones 2k and the other is 1920 by 1080. Ones running at 144 hz and the other at 60 hz. Don't know how much this information will help. Sorry if its a repost I took a quick look and didn't see anything.

**Comment by ChrisAnd1998** [comment]
Yep i will link this to #145
