### ISSUE TITLE
Use Monochromatic Dynamic Tray Icon

### ISSUE THREAD

**Issue by pc-v2** [ChrisAnd1998/FalconX-Center-Taskbar#123]
![image](https://user-images.githubusercontent.com/58063311/71366556-dbd9cd00-25d4-11ea-9980-3efd7b6ccc23.png)
it's not visible with colored taskbar,
and since windows introduce light mode, system tray can change to black icon

**Comment by Cabola** [comment]
could be fixed with a simple 1px white border around it

**Comment by ChrisAnd1998** [comment]
I have now seperated the settings window from FalconX in update 1.3.6.0.
There is no tray icon anymore.
