### ISSUE TITLE
App not DPI aware

### ISSUE THREAD

**Issue by BjornBakke** [ChrisAnd1998/FalconX-Center-Taskbar#125]
App windows is very small on 3000x2000 px screen 
![image](https://user-images.githubusercontent.com/1997921/71473638-18294b00-27d8-11ea-9ec1-9d0499ca7763.png)

![image](https://user-images.githubusercontent.com/1997921/71473655-29725780-27d8-11ea-8188-fba45eb04fc4.png)

![image](https://user-images.githubusercontent.com/1997921/71473712-8110c300-27d8-11ea-8610-055dd00187ed.png)

**Comment by ChrisAnd1998** [comment]
I have now seperated the settings window from FalconX in update 1.3.6.0.
So now the settings window will be a little blurry but, accessible again.
I may rewrite the settings window in a different language or WPF.
