### ISSUE TITLE
Toolbar display wrong after tray icon changed

### ISSUE THREAD

**Issue by liyafe1997** [ChrisAnd1998/FalconX-Center-Taskbar#127]
I have a folder toolbar in the right side in task bar:
![IMG1](https://user-images.githubusercontent.com/18359157/71486806-75dd8780-2818-11ea-8bad-92fefe37b295.jpg)

If I open a new software which have a icon on tray, it will look like this:
![IMG2](https://user-images.githubusercontent.com/18359157/71486869-aae9da00-2818-11ea-96e1-412a07c88665.jpg)

**Comment by liyafe1997** [comment]
I made a pull request to fix this. This may not a best solution but I hope it can provide you a reference.
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/pull/128

**Comment by ChrisAnd1998** [comment]
Thanks, i have been testing your suggestion and it kinda fixes the problem but, it makes the taskbar flicker again. I will try to find a way so it won't flicker.

**Comment by Cabola** [comment]
This is nothing new, it was in the older versions too [#96](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/issues/96)

**Comment by ChrisAnd1998** [comment]
Yep, i will have to close this one to avoid duplicates.

**Comment by liyafe1997** [comment]
What does flicker means?
I tested on my system it works well. I am on Windows 10 1909 18363.535:

![fdasfdasfdsa](https://user-images.githubusercontent.com/18359157/71520510-ce666080-28bc-11ea-86cd-3f21affe1014.gif)

**Comment by liyafe1997** [comment]
Oh I found it. If you run on Debug version exe it will flicker when RefrushExplorer, but if you use Release build it works well.

**Comment by ChrisAnd1998** [comment]
Well it keeps flickering on my side also in release without debugging. Sometimes it even stays on the left.

**Comment by liyafe1997** [comment]
> Well it keeps flickering on my side also in release without debugging. Sometimes it even stays on the left. :(

I see. Because it flicker too fast so it seems not flickering.
I test in a virtual machine it actually keeps flickering, and sometimes it even stays on the left.
I found only can animate if you set WM_SETREDRAW to false, but only can make the toolbar works by set it to true. When you set it to true, the icon will go to left so that the reason flickering.
I am figuring out how to deal with it, like make it redraw manually.

**Comment by ChrisAnd1998** [comment]
I hope you can find anything. I am also working on it atm.

**Comment by ChrisAnd1998** [comment]
I might have finally gotten it. I am still testing it though.
https://chrisandriessen.nl/web/img/2019-12-28%2009-51-51.mp4

Test version:
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.7.0_v3.zip

**Comment by liyafe1997** [comment]
Wow great job. Did you push the code to this repo?

**Comment by ChrisAnd1998** [comment]
Thanks! No not yet, it seems to work fine on a single monitor setup. When i connect another monitor it does a flicker so i will try to fix that too. I am also considering to remake the settings window in UWP style. 

I will push everything when i release 1.3.7.0 ;)

**Comment by ChrisAnd1998** [comment]
I have now also fixed that with:

```
 If Not TrayNotifyWidth = OldTrayNotifyWidth Then

                    If Not OldTrayNotifyWidth = 0 Then

                        If Not MSTaskListWClass.Current.BoundingRectangle.X = 0 Then

                            Dim rebar As AutomationElement = AutomationElement.FromHandle(GetParent(CType(MSTaskListWClassPtr, IntPtr)))
                            Dim offset = CInt(rebar.Current.BoundingRectangle.Left.ToString.Replace("-", ""))

                            Dim pos = MSTaskListWClass.Current.BoundingRectangle.X - offset


                            SendMessage(ReBarWindow32Ptr, WM_SETREDRAW, True, 0)
                            SendMessage(ReBarWindow32Ptr, WM_SETREDRAW, False, 0)


                            If Taskbar.Horizontal = True Then
                                SetWindowPos(MSTaskListWClassPtr, IntPtr.Zero, pos, 0, 0, 0, SWP_NOSIZE Or SWP_ASYNCWINDOWPOS Or SWP_NOACTIVATE Or SWP_NOZORDER Or SWP_NOSENDCHANGING)
                            Else
                                SetWindowPos(MSTaskListWClassPtr, IntPtr.Zero, 0, pos, 0, 0, SWP_NOSIZE Or SWP_ASYNCWINDOWPOS Or SWP_NOACTIVATE Or SWP_NOZORDER Or SWP_NOSENDCHANGING)
                            End If

                        End If
                    End If

                End If
```
