### ISSUE TITLE
/New settings/ Add back the option to end FalconX

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#129]
(I am sure you already have this on your to-do list, but will open the issue anyway to keep things organized.)

In the new settings there is no option to end the app other than reboot or taskmanager, which is not really convenient. Also since the app is portable only without installer it is needed to manually end the process anytime I want to copy a new update over. So I personally consider this pretty important, at least for public builds.

But I understand that migrating to the new separated settings takes some time and effort, so no pressure :).

**Comment by ChrisAnd1998** [comment]
Yep, i just added it a couple minutes ago XD

**Comment by Martin5001** [comment]
Great.
