### ISSUE TITLE
Use message hook to call TaskbarCalculator() instead of loop

### ISSUE THREAD

**Issue by liyafe1997** [ChrisAnd1998/FalconX-Center-Taskbar#130]
I think use a message hook to make a callback function, when a new window open or a new taskbar icon appeared, to call TaskbarCalculator() instead of loop and Thread.Sleep. Because it makes the animate not in time, and waste resource(When no new icon coming).

I am figuring out how to do that.

**Comment by ChrisAnd1998** [comment]
Well i have already done it that way but, resulted in much higher performance usage.
