### ISSUE TITLE
FalconX does not center taskbar on start

### ISSUE THREAD

**Issue by iamthekings5** [ChrisAnd1998/FalconX-Center-Taskbar#133]
Hello,

I noticed that no matter which method I use to start FalconX, or if a delay is applied, FalconX will launch but it will not center my taskbar. I can see the FalconX process in task manager. I will have to manually launch FalconX again to get it recenter.

I've tried using Task Scheduler (and with a 2 min timer set) and putting FalconX in the startup folder. Neither will center my taskbars.

I suspect it has something to do with having multiple monitors. I use a laptop and an external display, with the external display set as my main.

**Comment by ChrisAnd1998** [comment]
Well FalconX, should just be working. Also multi monitors are supported so there can't be an issue there.

Can you give me some info about your PC?

**Comment by iamthekings5** [comment]
> 
> 
> Well FalconX, should just be working. Also multi monitors are supported so there can't be an issue there.
> 
> Can you give me some info about your PC?
> Your current taskbar settings?
> And are you using the store version or the normal version?

I'm using Windows 10 Home Insider Preview Version 2004 19536.1000, running a laptop connected to an external monitor. I set up the external monitor as my main display.

Taskbar settings are all default except I ticked run at start-up. I'm running translucent taskbars alongside this plugin, but I have tried running FalconX without it running and the same thing happens.

I have also tested this on both the store version (1.3.5.0) and the latest version available on github (1.3.7.0). The same issue occurs on both. Also worth noting I even tried using Task scheduler to run FalconXSettings.exe to see if it would fix the issue, but same thing happened. I always see FalconX.exe in Task Manager but the taskbar won't shift until I launch the task manually.

**Comment by ChrisAnd1998** [comment]
I did not test build 2004 yet so i will be testing that in a couple days but, i am sure that works just fine. Also very weird that it works when you launch it manually. Any AV installed?

I actually meant your Windows taskbar settings because, there is one option that could give issues. 
The option "Show taskbar buttons on" should be "All taskbars" like in the screenshot below.

![3YkKj](https://user-images.githubusercontent.com/50437199/71667447-69e84d00-2d65-11ea-9d4e-4747c603cb87.png)

**Comment by iamthekings5** [comment]
> 
> 
> I did not test build 2004 yet so i will be testing that in a couple days but, i am sure that works just fine. Also very weird that it works when you launch it manually. Any AV installed?
> 
> I actually meant your Windows taskbar settings because, there is one option that could give issues.
> The option "Show taskbar buttons on" should be "All taskbars" like in the screenshot below.
> 
> ![3YkKj](https://user-images.githubusercontent.com/50437199/71667447-69e84d00-2d65-11ea-9d4e-4747c603cb87.png)

Hey, that solved the issue! I feel so silly now. Was there a warning that I failed to read or something like that? Sorry for wasting your time. Cheers.

**Comment by ChrisAnd1998** [comment]
Don't feel silly XD i didn't warn people about this because, it's a very rare taskbar option. And i discovered that this option doesn't work in december.

Glad it works now :)

**Comment by ExpiredBananas** [comment]
I have the same problem but I'm on laptop with only one taskbar so that can't solve my issue. I'm on version 1.4.5.0 and when my computer switches on, it doesn't center until i open the falconx.exe programme.

**Comment by nightmarewolf62** [comment]
@Jonekkelis Ok, you helped me but what the hell is that Z: Disk XD?

**Comment by Jonekkelis** [comment]
O

> @Jonekkelis Ok, you helped me but what the hell is that Z: Disk XD?

Oh shit forgot that so umm hows your day been?
