### ISSUE TITLE
No settings icon in task bar

### ISSUE THREAD

**Issue by Senk0n** [ChrisAnd1998/FalconX-Center-Taskbar#135]
After FalconX from MS was updated app icon gone from task bar

1.3.5.0 - https://i.imgur.com/7fFabie.png
1.3.7.0 - https://i.imgur.com/7aGpudp.png

**Comment by ChrisAnd1998** [comment]
Hi @Senk0n ,

Yes, thats actually a new feature. I have split up the settings gui from the main application.
So now you have (FalconX) and (FalconX Settings)

I completely got rid of the tray icon ;)

![1](https://user-images.githubusercontent.com/50437199/71761347-0af01880-2eca-11ea-84b6-adf49cdabc21.png)

![2](https://user-images.githubusercontent.com/50437199/71761348-0d527280-2eca-11ea-94e2-49e438c9c035.png)
