### ISSUE TITLE
/Question/ Difference between "Run at startup" x "Create logon schedule"

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#137]
I know this is not much a feedback or bug related thing, but I am little confused what is the difference between registering a task schedule vs. toggling on the "Run at startup" option. (I think this is important to know not just for a general usage but more for testing - when I know the expected behaviour, then I can report enventual bugs.)

**Comment by ChrisAnd1998** [comment]
If i add a program to startup it will be added to a list with other programs to run at startup when you login Windows will cycle through every program that has been assigned to run at startup. So in most cases this will take sometime for FalconX to start.

A scheduled task will trigger based on the event you set. For FalconX i have setup a "Logon" trigger.
The "Logon" trigger will trigger as soon as you login to Windows. I have setup a delay of 3 seconds to make sure "Explorer" is started. 

So the FalconX "task" will start a little before "Explorer" and waits for 3 seconds to start "FalconX.exe".

**Comment by FrankGHB** [comment]
I'd expect one setting to exclude the other ? Either you run fx at startup OR when logging on so when setting to run at startup the "run at at logon" task should be deleted (after a confirmation dialog) and vice versa. I thought you created the run at logon option to deal with issues where fx does not launch with the run at startup option set. I continued to have that issue up until 1.3.7 but not consistently e.g. not at every reboot. Very strange.

**Comment by ChrisAnd1998** [comment]
It still needs more testing. It hasn't failed on my testing pc's and pc's on my work. The normal will be run at start up will be disabled if you create a logon task and vise versa.

**Comment by Martin5001** [comment]
I don't know about the performance or how it would be feasible but wouldn't it be better to somehow detect explorer starting instead of setting the three seconds limit hard – my thought is that different devices may load explorer quicker or slower depending on the hardware so the time limit might change. But I don't know, this is just my theory.

**Comment by FrankGHB** [comment]
After PC sleep, FX stops. tested with 1.3.8

**Comment by Martin5001** [comment]
This may be related: #140

**Comment by ChrisAnd1998** [comment]
I will be testing more in a couple days 😉.

The delay is to be able to start the FalconX app when it's in store mode. I can also do it with cmd or powershell but, will show a console window for a second.

Thanks for notifying me about the issues! 😁

**Comment by FrankGHB** [comment]
Is having a store mode important?

**Comment by ChrisAnd1998** [comment]
Sorry, i meant when it runs as a packaged Windows Store App.

The regular and the store version are both identical. If it runs from the store it will detect that. Store apps cannot be run by their exe but, only through a command with the package name.

**Comment by FrankGHB** [comment]
After FX reverts back to the left (after a sleep period) I start the settings program which seems to start FX. Why is that ? It's only a settings program ? Desperately need a good working FX on my 49" screen !

**Comment by Neobond** [comment]
Yeah clearly it is not working, if I try just Run at Startup or just use the logon task it takes ages to start, but this morning after 30 mins it still hadn't centered the icons, and this is a recurring issue, when I checked FalconX settings I see that Run at Startup and the login task are _both_ enabled, which is not the supposed behavior. Please advise because it is annoying that this app is the last to start or simply doesn't start at all as what happened this morning, despite seemingly having both startup options checked (which shouldn't be possible).

![SNAG-0001](https://user-images.githubusercontent.com/42996358/72135449-d1665400-3386-11ea-8048-8a2c8acd9c2d.png)
![SNAG-0000](https://user-images.githubusercontent.com/42996358/72135452-d1665400-3386-11ea-9e3c-9d00ba00607d.png)

**Comment by FrankGHB** [comment]
Actually I don't think it is the PC sleep function causing FX to quit and shift the taskbar back to the left. I think it has to do with the display going to sleep. I have the following setup: 49" monitor hooked up to laptop via hdmi. 49" set as primary display. Taskbar ONLY shown on the primary display.
