### ISSUE TITLE
Version 1.3.8.0 McAfee is reporting virus

### ISSUE THREAD

**Issue by lwetzel1** [ChrisAnd1998/FalconX-Center-Taskbar#139]
The FalconX.exe  file is showing Version 1.3.8.0 having a Virus and is being deleted by McAfee AntiVirus Plus.  I copied the previous version of FalconX.exe to replace it and there is no problem.  
This is the download version not the Windows Store version
WHAT's UP with that?

**Comment by Martin5001** [comment]
Does McAffee have a way to submit false positives for manual review? I would send it to them.

**Comment by lwetzel1** [comment]
Seems to me that should be the authors problem to solve.
