### ISSUE TITLE
McAfee is reporting this as a virus.

### ISSUE THREAD

**Issue by lwetzel1** [ChrisAnd1998/FalconX-Center-Taskbar#144]
![image](https://user-images.githubusercontent.com/54991318/72269635-8c8e2780-35e9-11ea-9fc3-ebb3ca64abe3.png)

This was happening only with the download version but is now happening with the Windows Store version I paid for.  NEED TO LOOK INTO THIS.......ASAP

**Comment by Martin5001** [comment]
Hello @lwetzel1,
I checked VirusTotal and noticed that it does not detect it, so it´s probably the behavioral analysis what is causing the problem, not the definitions. (It makes sense that the antivirus "does not like" when something changes windows taskbar even if it is harmless.)
**I have sent an email to McAfee, but I cannot provide them all the info you can** (their KB mentions McAfee version etc. which I don´t know) so maybe you should [submit it](https://service.mcafee.com/webcenter/portal/oracle/webcenter/page/scopedMD/s55728c97_466d_4ddb_952d_05484ea932c6/Page29.jspx?wc.contextURL=%2Fspaces%2Fcp&locale=en-US&articleId=TS102053&_afrLoop=93066947499702&leftWidth=0%25&showFooter=false&showHeader=false&rightWidth=0%25&centerWidth=100%25#!%40%40%3FshowFooter%3Dfalse%26locale%3Den-US%26_afrLoop%3D93066947499702%26articleId%3DTS102053%26leftWidth%3D0%2525%26showHeader%3Dfalse%26wc.contextURL%3D%252Fspaces%252Fcp%26rightWidth%3D0%2525%26centerWidth%3D100%2525%26_adf.ctrl-state%3D1atn3jt3s2_9) yourself too in case they won´t bother with my submission.

**Comment by ChrisAnd1998** [comment]
McAfee is causing a lot of issues lately. I already contacted them but, this is not fixable. FalconX is not flagged but, it seems that the automated detection system doesn't like FalconX's behavior. You will need the make an exclusion in McAfee for FalconX or Allow it.
