### ISSUE TITLE
Dont Taskbar Icon 1.3.8.0

### ISSUE THREAD

**Issue by Pipenbrok** [ChrisAnd1998/FalconX-Center-Taskbar#146]
Hello everybody,
Now i have the Problem thats FalconX 1.3.8.0 is running by pc start and Works... Great 💯 
same problem by the 1.3.7.0...

Now i have the problem that the taskbar is no longer an icon that I can click on :)
![14-01-2020_16-45-21](https://user-images.githubusercontent.com/26583508/72358704-47ebb480-36ed-11ea-9792-85d63527ff2e.jpg)

what is the "hint" so that i can see the surface again ?

thanks for the Help
### André
---
Computer Science Expert Subject Area: Software Development

**Comment by ChrisAnd1998** [comment]
I got rid of the tray icon in update 1.3.6.0 ;)
The settings and the main program are now split up into 2 separate programs.

In your start menu you can find it under "FalconX Settings".


![1](https://user-images.githubusercontent.com/50437199/72374558-ca36a180-370a-11ea-9a65-8393ac444e61.png)
