### ISSUE TITLE
inconsistent

### ISSUE THREAD

**Issue by Marshallaide** [ChrisAnd1998/FalconX-Center-Taskbar#148]
I am finding having setup device, it keeps undoing itself and switching itself  back to  original state frequently.
Non consistent.

**Comment by ChrisAnd1998** [comment]
Does this testing build fix it?

**Comment by Marshallaide** [comment]
! C:\Users\Graham Marshall\Downloads\1.3.9.0_v1 (1).zip: Cannot create C:\Users\Graham Marshall\Downloads\FalconX.exe
  Access is denied.
! C:\Users\Graham Marshall\Downloads\1.3.9.0_v1 (1).zip: Cannot create C:\Users\Graham Marshall\Downloads\Interop.UIAutomationClient.dll
  Access is denied.
! C:\Users\Graham Marshall\Downloads\1.3.9.0_v1 (1).zip: Cannot create C:\Users\Graham Marshall\Downloads\UIAComWrapperX.dll
  Access is denied.
Does this answer your question?

**Comment by Marshallaide** [comment]
Eventually opened download and replaced original.   Will let you know outcome.
Thanks for replying.

**Comment by ChrisAnd1998** [comment]
no problem :),

I also have v2 not necessary for testing this issue but, is the most recent testing built.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.9.0_v2.zip

**Comment by Marshallaide** [comment]
Hi. Trying out latest V2.
