### ISSUE TITLE
"Enable taskbar styling" turns off each time computer restarts

### ISSUE THREAD

**Issue by erictet** [ChrisAnd1998/FalconX-Center-Taskbar#150]
Hi there,

I bought the app mainly for the transparency feature, however the "Enable taskbar styling" checkbox is always unchecked when my computer turns on. After opening FalconX Settings I can re-check the box, save and close and it works fine, but reverts back to "off" after restarting. Is this a known issue? Please let me know if you need any more information.

Cheers,
Eric

**Comment by ChrisAnd1998** [comment]
Yes, this seems to happen to more people. I hope to get a fix for the next update.

**Comment by ChrisAnd1998** [comment]
I have submitted version 1.4.1.0 to the store. It can arrive within 2 days.
Can you let me know if it's fixed when you get the update?

**Comment by erictet** [comment]
Hey mate,

It's been working perfectly for the last ~7 days (not sure what's caused it to) but I'll let you know if anything changes in the new update.

Cheers

**Comment by ChrisAnd1998** [comment]
Thanks :) for letting me know!
