### ISSUE TITLE
Setting window: tabs hide behind the title bar 

### ISSUE THREAD

**Issue by payambordbar** [ChrisAnd1998/FalconX-Center-Taskbar#151]
Version : 1.4.0.0
Resolution : 1920*1080
Scale: 125%

![Annotation 2020-01-21 015445](https://user-images.githubusercontent.com/45229646/72761782-560c6a00-3bf2-11ea-9267-05f40f169f3b.jpg)

**Comment by ChrisAnd1998** [comment]
Yep, i need them to switch tabs in the form designer. I left them open because, it's a testing build. It will be closed up on release.
