### ISSUE TITLE
FalconX not downloaded

### ISSUE THREAD

**Issue by kikokill** [ChrisAnd1998/FalconX-Center-Taskbar#152]
so when I click FalconX nothing pops up as well as when I press save or restart on falcon settings it just sends me to my files and nothing happens as well as no settings work. I purchased FalconX from the Microsoft store.

**Comment by ChrisAnd1998** [comment]
The store version needs to be launched by a command. I think that command doesn't work on your current version of Windows 10. Can you tell me what build of Windows 10 you are using?

**Comment by ncodee** [comment]
Sorry to hijack this post, just wanted why the MS Store version is always a release behind? 
I'm assuming it's done on a rollout basis? thanks

**Comment by ChrisAnd1998** [comment]
@ncodee it actually takes 3 business days for Microsoft to publish the store package. And sometimes me uploading new versions in a short period of time can cause it to add up. Also testing builds like 1.4.0.0 atm won't be released to the Store. 1.3.9.0 is currently the latest release and also published to the store.

**Comment by kikokill** [comment]
When I get back home I’ll check to see what windows 10 I have.
