### ISSUE TITLE
Cannot reset the taskbar to original position and cannot permanently remove FalconX.

### ISSUE THREAD

**Issue by Noobgamer0111** [ChrisAnd1998/FalconX-Center-Taskbar#153]
Dear @ChrisAnd1998 ,

Your project is really cool but it's kind of annoying that you cannot revert the original position of the taskbar and the apps to their original position. Also, there is no uninstall/actual stop feature that works.
Also, this program does not show up in Programs and Features in Control Panel and in the Apps in Windows Settings.

Thanks,

Noobgamer0111

**Comment by ChrisAnd1998** [comment]
Thanks :) With the "FalconXSettings.exe" you can stop FalconX and set the original taskbar position back. FalconX is a portable application so it doesn't require to be installed wich means it does'nt require to be in the programs and features list. You can simply remove it by first closing it and then removing the files.
