### ISSUE TITLE
Doesn't recognize well primary bar

### ISSUE THREAD

**Issue by InsertCoinPls** [ChrisAnd1998/FalconX-Center-Taskbar#157]
When I enable the option "Center primary bar only" the app only center the secundary bar.

![image](https://user-images.githubusercontent.com/48566760/72977507-fe7a2400-3dd4-11ea-8e37-ff3203ab77fa.png)

**Comment by ChrisAnd1998** [comment]
Hmm seems like its finding the second taskbar earlier than the primary taskbar i'll look into it.

**Comment by ChrisAnd1998** [comment]
I have added the fix to the pre-release 1.4.0.0 v3
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.4.0.0
