### ISSUE TITLE
FalconX slow to start

### ISSUE THREAD

**Issue by Neobond** [ChrisAnd1998/FalconX-Center-Taskbar#158]
So I have to keep manually starting FalconX on Windows 10 1909 because the autostart option does not work either as a task or startup option at all.

In addition I had to whitelist FalconX.exe with Windows smartscreen, which I have to do with each new version, which is why I think it might not start on its own, but more to the point, when I manually start FalconX after booting Windows it doesn't actually center the taskbar for 3+ minutes. Why? Why doesn't this app do the basic things it is built for lol?

Also I would like to again complain at the lack of settings in the tray for 1.3.9.0

**Comment by Neobond** [comment]
![SNAG-0000](https://user-images.githubusercontent.com/42996358/73010777-56378000-3e13-11ea-934e-12cc6d3a2101.png)

This is also confusing to me.. why disable a perfectly valid button in the OS and then add another one in a p;lace Windows users don't usually go to close things? :P

**Comment by ChrisAnd1998** [comment]
Well FalconX should just work fine on startup also the task schedule will start it after 3 seconds when you login to windows. So there may be something preventing FalconX from starting properly on your current installation. I need more info about your windows installation to be able to make a fix.

**Comment by Neobond** [comment]
Chris, tell me what to do! :)

**Comment by ChrisAnd1998** [comment]
It's Windows 10 1909
What about Antivirus software?
Other programs that run at start-up?

The option "Show taskbar buttons on" should be "All taskbars" like in the screenshot below.
![71667447-69e84d00-2d65-11ea-9d4e-4747c603cb87](https://user-images.githubusercontent.com/50437199/73018964-ee893100-3e22-11ea-9b51-23c5410e7ebd.png)

**Comment by Neobond** [comment]
![SNAG-0001](https://user-images.githubusercontent.com/42996358/73019765-88051280-3e24-11ea-9485-86750f21bdc5.png)
I have loads of crap starting up (hate it) but I only have one display (49" Samsung CRG90) so the multiple displays thing is greyed out for me.

![SNAG-0002](https://user-images.githubusercontent.com/42996358/73019862-b71b8400-3e24-11ea-8330-10f5c11ebbae.png)

**Comment by ChrisAnd1998** [comment]
Yep, the start-up delay could be caused by all those applications. 

Thats why i made an option the make a taskschedule. Does that work?

You should really clean that up though... ;)

**Comment by Neobond** [comment]
Hello. I uninstalled some crap and disabled some programs from startup and task scheduler that I don't need and suddenly falconx is starting quickly from the task scheduler option.

There definitely was a program blocking it, but I have no idea which one?  Could be Gigabyte app center or Intel driver update checker I guess (both disabled now).

![SNAG-0000](https://user-images.githubusercontent.com/42996358/73077419-6d807700-3ec0-11ea-897f-414f62ea4d64.png)

**Comment by ChrisAnd1998** [comment]
Glad you fixed the issue :)

I can go through the list with the programs you had at startup in a virtual machine later. To identify which one caused the issue.
