### ISSUE TITLE
Task from the scheduler isn't run

### ISSUE THREAD

**Issue by Robzyy** [ChrisAnd1998/FalconX-Center-Taskbar#161]
I have created the logon task via the button from the settings GUI some time ago and for some reason it never opens FalconX, as it should....
I have tried deleting and re-adding it but it didn't change things at all
After that i have opened the Task Scheduler to see if it actually exists and if it is configured correctly and these are the results:
1. The task exists
2. The action of opening the app is set correctly
3. The trigger also seems set correctly
4. In the 'History' tab there is absolutely nothing! ("Number of events:0")
So i guess the trigger is messed up?
N.B.: I have never modified the task!
So yeah that's my issue....

**Comment by ChrisAnd1998** [comment]
Does this happen with the store or regular version?
I have had no issues with it but, i'm getting multiple reports about this issue. I'm still figuring out what causes this issue. Feel free to modify the task to see what does work if you like.

In Task Scheduler you can right click on the "FalconX" task and select "Run" to see if it even launches FalconX.

**Comment by Robzyy** [comment]
1. I am using the Windows Store version.
2. Just booted up the PC and clicked on the run button in Task Scheduler and it works as intended
I will try to mess with the task settings and report back if i find something that works for me

**Comment by Robzyy** [comment]
Looks like I've made it functional!
I will post some pics together with this message for you to analyze the differences.
![Annotation 2020-01-31 135724](https://user-images.githubusercontent.com/54444619/73537665-afb23700-4431-11ea-92a4-c151bed8bc21.png)
![Annotation 2020-01-31 135526](https://user-images.githubusercontent.com/54444619/73537667-b04acd80-4431-11ea-8647-37c95bc2200b.png)
![Annotation 2020-01-31 135648](https://user-images.githubusercontent.com/54444619/73537669-b04acd80-4431-11ea-8ab8-ddc5f6aacfef.png)
The rest is unmodified.

**Comment by ChrisAnd1998** [comment]
Thanks for figuring it out 👍😀.

I will look into it tomorrow.

**Comment by Robzyy** [comment]
I have been messing with the task and I believe the delay might be the problem....When I set it to 30 secs it works like a charm, but when i set it to 3 or 5 secs it doesn't even start the process...Will still look into it more tho.

**Comment by ChrisAnd1998** [comment]
Thanks for testing it out much appreciated 😁👍.

I didn't get the time to get into it yet 😓.

What if you set the delay to just 5 sec and make it restart every 5 seconds if it fails for 10 times or so?

**Comment by Robzyy** [comment]
The option where it reruns the task if failed has a minimum limit of 1 minute and that's not cool.
I think the best option is to set the delay to 10 seconds (just like i've set it now) so that it can work flawlessly on every slow hard disk *cries*
