### ISSUE TITLE
Symantec Endpoint detection

### ISSUE THREAD

**Issue by nevara** [ChrisAnd1998/FalconX-Center-Taskbar#163]
Hello, 
your current version is detected by Symantec once again. Please file a false positive report here:

https://submit.symantec.com/false_positive/standard/

I tried to do it for you, but I cannot pass the captcha for the life of me.

**Comment by ChrisAnd1998** [comment]
Allright i'll try to.

**Comment by ChrisAnd1998** [comment]
Allright i successfully submitted the false positive ;)

**Comment by ChrisAnd1998** [comment]
Response:

> In relation to submission 192153.
> 
> Upon further analysis and investigation we have verified your submission and as such this detection will be removed from our products.
> 
> The updated detection will be distributed in the next set of virus definitions, available via LiveUpdate or from our website at https://www.symantec.com/security_response/definitions.jsp
> 
> Please note that whitelisting can take up to 24 hours to take effect.
> 
> Decisions made by Symantec are subject to change if alterations to the Software are made over time or as classification criteria and/or the policy employed by Symantec changes over time to address the evolving landscape.
