### ISSUE TITLE
Falcon X doesn't launch at startup even though it's active under "startup" tab in taskmanager.

### ISSUE THREAD

**Issue by HyperwaveGlitch** [ChrisAnd1998/FalconX-Center-Taskbar#165]
I've experienced this a lot lately. Additionally, it doesn't open when I manually launch "Falcon X", I have to launch "FalconX Settings" for it to launch. 

Win 10 Pro, Intel i9 9900K, Asus Z390-F, lots of RAM. 

Note that I'm also running wallpaper engine at startup. I have disabled all taskbar options in WE, but I thought I should mention it since they both have an impact on windows taskbar, in case it's relevant.

**Comment by Robzyy** [comment]
Do you use the Windows Store or website version?

**Comment by ChrisAnd1998** [comment]
Have you tried the taskschedule option? It may work better but, there are some things to fix.

**Comment by HyperwaveGlitch** [comment]
> Do you use the Windows Store or website version?

Windows store.

**Comment by HyperwaveGlitch** [comment]
> Have you tried the taskschedule option? It may work better but, there are some things to fix.

Yes, I have. It seems like it starts correctly now, but I only changed it recently and Falcon X has been working since then. Than being said, Falcon X has been working without it for the most part, so I'm not 100% sure if the problem is solved or I've just been lucky since  then. I'll let you know if the problem comes up again.

**Comment by ChrisAnd1998** [comment]
Allright, glad to hear it's working :)
