### ISSUE TITLE
Multiple monitors: if the primary taskbar is on a different side than the secondary taskbars, the secondary taskbar's icons are not centered.

### ISSUE THREAD

**Issue by EthanRDoesMC** [ChrisAnd1998/FalconX-Center-Taskbar#166]
![its so close](https://user-images.githubusercontent.com/11563487/73903015-572dd000-485d-11ea-9259-bf841eefc6f9.png)

FalconX is so close to being perfect for my setup, except for this one bug.

**Comment by ChrisAnd1998** [comment]
Well i guess i have to make FalconX to detect the taskbar orientation per screen 🤔.

**Comment by ChrisAnd1998** [comment]
I've added it in the pre-release (V2)
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.4.0.0

**Comment by EthanRDoesMC** [comment]
You’re amazing, thank you so much :)
