### ISSUE TITLE
**Solution** to my previous issue!

### ISSUE THREAD

**Issue by Robzyy** [ChrisAnd1998/FalconX-Center-Taskbar#171]
Hello, Chris!! I saw that you recently modified the action the task from the scheduler is supposed to run by using powershell. **You made it functional!** but there is a little problem: the powershell window stays wayyy too much on the screen for some of us, including me :(
   After a bit of searching and investigation I have made a VBS script which runs the powershell command silently! I'll post it here so you can see what I did: 
[FalconX.txt](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4208994/FalconX.txt)  (rename to *.vbs)
   The original script for running powershell silently was taken from here: https://www.faqforge.com/windows/how-to-execute-powershell-scripts-without-pop-up-window/ . I just modified the "-command C:\Users\howtoforge\Desktop\loop.ps1"
with your "start-process" command

   Hope you don't mind opening a new "issue" for this. I just wanted to make sure you will see this :)

**Comment by ChrisAnd1998** [comment]
Great to hear that it works! :)
I will definitely give this a try!

**Comment by ChrisAnd1998** [comment]
I have added it ;)
https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.4.1.0

It will take some time for it to appear in the store...
