### ISSUE TITLE
I can't change settings?

### ISSUE THREAD

**Issue by Duckrinium** [ChrisAnd1998/FalconX-Center-Taskbar#174]
I don't know if it is because of #173 error that appearing or something else, but it seems like I can't change settings, saving and restarting doesn't work and it returns to current settings
![gHl9t5MbhE](https://user-images.githubusercontent.com/37019004/75057806-d7edfc80-54ea-11ea-82a0-b2e55ffc9773.gif)

**Comment by ChrisAnd1998** [comment]
Are you using the regular or the store version?

**Comment by Duckrinium** [comment]
> Are you using the regular or the store version?
> 
> (The index was outside...) Error will be fixed next update.

Store

**Comment by blackluster117** [comment]
I have this same issue with the regular version. It will retain settings that I set for a bit, then revert back to default settings.

**Comment by ChrisAnd1998** [comment]
@Duckrinium @blackluster117 
Is your Windows 10 installation maintained by someone else? Like an organisation. 
What build of Windows 10 is it?
What edition (Home, Pro etc..)?
Any Antivirus software installed?

I am asking this so i may be able to reproduce your situation.

**Comment by ChrisAnd1998** [comment]
1709 does not support taskbar styling.
Does this fix the saving issues?

[1.4.3.0_Test.zip](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4241257/1.4.3.0_Test.zip)

**Comment by ChrisAnd1998** [comment]
I reproduced the issue and fixed it in Windows 1709. Feel free to open a new issue if it still occurs.
