### ISSUE TITLE
"Center primary taskbar only" doesn't work when the taskbar is shown at right side

### ISSUE THREAD

**Issue by skuldYi** [ChrisAnd1998/FalconX-Center-Taskbar#175]
the feature do work when the taskbar is shown at the bottom. but when it is on the right side, the task icons seems to be at the center of the whole taskbar, instead of between search and tray; and icons at bottom can be covered by the tary.

**Comment by ChrisAnd1998** [comment]
I didn't actually code it to work with the vertical taskbar so i will mark it as a "feature request"
