### ISSUE TITLE
index was outside the bounds of the array

### ISSUE THREAD

**Issue by 0neEyed** [ChrisAnd1998/FalconX-Center-Taskbar#177]
when I restart or open falconx, this notification pops up. How can I fix it?
![image](https://user-images.githubusercontent.com/41566020/75112795-cd15a200-5679-11ea-8187-6bb097135f90.png)

**Comment by ChrisAnd1998** [comment]
1.4.1.0?

**Comment by 0neEyed** [comment]
yes, it's 1.4.10

**Comment by ChrisAnd1998** [comment]
This has been fixed in 1.4.2.0 ;)
