### ISSUE TITLE
Index out of bounds array

### ISSUE THREAD

**Issue by claudiu99lux** [ChrisAnd1998/FalconX-Center-Taskbar#179]
Hi! The app hasn't been working for some time now for me, everytime i try to start the app, a pop-up saying "Index out of bounds array!" appears. Couldn't find a fix to this!

**Comment by ChrisAnd1998** [comment]
version 1.4.1.0 ?

**Comment by Kaleb-Jen-1619** [comment]
This happens when the app is opens, but once the error message is dismissed then the app runs properly

**Comment by ChrisAnd1998** [comment]
This has been fixed in 1.4.2.0 ;) Latest is 1.4.3.0
