### ISSUE TITLE
Explorer.exe CPU usage idles around 20% when FalconX is active

### ISSUE THREAD

**Issue by Dragontech97** [ChrisAnd1998/FalconX-Center-Taskbar#185]
Latest build 23.02.2020-1.4.3.0 Windows 10 1909
Monitor task manager explorer.exe usage. Fresh reboot. Explorer.exe idles around 15-20% CPU (Intel i7 4700HQ)
Went to ProcessExplorer briefly and seems like shcore.dll was the culprit, involved in possible system dpi scaling? Need to debug some more; turned off TranslucentTB and result was similar enough where I don't think it's TransTB.
Lastly, I went to FalconX settings and clicked on Stop button to return explorer shell to normal and the CPU usage for explorer.exe went back to 0%(no explorer windows open). Clicked on Restart button and after FalconX starts CPU usage for explorer.exe reads ~20% again.

**Comment by ChrisAnd1998** [comment]
Hmm, i also have to debug this more. It runs fine at my end. (Intel i7 8700K)

![exp](https://user-images.githubusercontent.com/50437199/75350193-5f01f280-58a6-11ea-8834-3f5f06eee065.jpg)

**Comment by Dragontech97** [comment]
Yep, will do some debugging as well
![Screenshot (30)](https://user-images.githubusercontent.com/10717304/75374205-d0877400-5899-11ea-89fe-ae0b623f71ac.png)
![Screenshot (29)](https://user-images.githubusercontent.com/10717304/75374206-d1200a80-5899-11ea-824a-e100ef689ad4.png)

**Comment by Dragontech97** [comment]
Quick update. Did a system restart and watched cpu usage right after startup. Same result. Took a screenshot of the process explorer page. I also made a dump of the explorer process, but its quite huge so figuring out how to upload it.
![Annotation 2020-02-26 132300](https://user-images.githubusercontent.com/10717304/75375289-c9f9fc00-589b-11ea-9be8-23fbdacd49f9.png)

**Comment by Buckstermcgee** [comment]
Seeing the same issue. Started happening after last update. Both Windows Explorer and FalconX have about 20% combined usage when on and disappears when FalconX is stopped. Persists after restart. 

FalconX on/running
![image](https://user-images.githubusercontent.com/61520960/75386908-77770a80-58b0-11ea-82a7-43e71a2d1d0b.png)

FalconX stopped
![image](https://user-images.githubusercontent.com/61520960/75387006-a2615e80-58b0-11ea-9fc8-5398ca29acd1.png)

**Comment by ChrisAnd1998** [comment]
@Buckstermcgee Last update i added the option to change the "refresh rate" it should be 400 ms by default can you see what it's set to now? It's located in the "Extra options" tab.

**Comment by Crocodile73** [comment]
yeah i have this issue as well, running 1909 x64

**Comment by Buckstermcgee** [comment]
My "refresh rate" was set at 400ms, which I first noticed after trying to troubleshoot the CPU usage and opened the FalconX settings. I have tried changing the refresh rate, but no values seem to affect CPU usage, neither negatively or positively, nor do I see any behavioral change when changing the refresh rate value, saving, restarting, etc. The reaction time of when the icons start moving appears identical whether it's set 0ms, 400ms, 2000ms, or anything else. The reaction/refresh rate also does seem to be faster than previous builds that did not have an option to adjust the refresh rate, so I would agree that this is likely the culprit, but at least for my machine, the refresh rate slider does not appear to be working as it apparently is set at a static value, regardless of what the slider shows.

**Comment by ChrisAnd1998** [comment]
@Buckstermcgee Weird, does this make a difference?
[FalconX.zip](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4262345/FalconX.zip)

**Comment by Buckstermcgee** [comment]
running that .exe does stop the excessive cpu usage, but icons no longer update their position, they just stay in the middle, even when new windows are brought onto or removed from that monitor.

![image](https://user-images.githubusercontent.com/61520960/75460417-70530980-594f-11ea-9b8a-d1a5be1000ab.png)

![image](https://user-images.githubusercontent.com/61520960/75460450-7c3ecb80-594f-11ea-8ea5-04b68486f11c.png)

reopening my installed version of FalconX or the FalconX settings app reverts to the previous behavior of fast refresh rate and high CPU usages.

**Comment by Crocodile73** [comment]
mine has been corrected with that file also, and my icons are fine, they are updating position. @Buckstermcgee did you revert back too 400ms?

**Comment by Duckrinium** [comment]
Can relate
![Taskmgr_gqYodpgVBZ](https://user-images.githubusercontent.com/37019004/75473509-5bee2b80-59a6-11ea-9a8d-0c2df214714c.png)
![Taskmgr_8vMMDS0DpY](https://user-images.githubusercontent.com/37019004/75473511-5c86c200-59a6-11ea-99d5-e9cf190ac1e0.png)

**Comment by Dragontech97** [comment]
@ChrisAnd1998 Big update: Found out that it's only the **Windows Store version of FalconX that is having cpu usage** issues on my end. When I use both the latest release 1.4.3 from the repo and the new zipped exe with it both work normally with explorer.exe under 5% usage (still a bit high for idle but more manageable than 20% previously). FalconX itself was the normal ~0% idle. Exiting out of the win32 version and opening the Windows Store version caused the explorer.exe usage to go back up to ~20%. I use the Store version mostly for automatic updates so its the latest Store version as well and I have the Store version to automatically launch on system startup as well so it does seem to be the Store version with the issues atm. Haven't tested the refresh rate slider, but everything else seems to be stable.

**Comment by ChrisAnd1998** [comment]
@Dragontech97 Well, the store version is actually the same win32 application as the regular one. FalconX detects if it's running regularly or from the store. If it's running from the store it will save the settings using powershell because, it always fails with the normal way due to permissions. You should try opening the settings window and set the refresh rate to 400 or if it already is save it anyway. The test i uploaded above checks for the refresh rate setting. If it is lower than 10ms like 0 it will force 10ms. 10ms is still very fast but, will make FalconX run at 0.3% CPU usage at idle on my end so 5% is still way to high. I am having a hard time trying to reproduce this 😩.

**Comment by Crocodile73** [comment]
@ChrisAnd1998 its was both for me. When i replaced the exe you posted and opened settings the refresh was at 0, it gave me 5-7% cpu useage. I changed it too 400 and saved, and that corrected it for me.

**Comment by ChrisAnd1998** [comment]
@Crocodile73 That's exactly i was expecting thanks for the confirmation! 😁

Here's a complete test version of 1.4.4.0
[FalconX_1.4.4.0_Test_v1.zip](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4263633/FalconX_1.4.4.0_Test_v1.zip)

**Comment by Crocodile73** [comment]
@ChrisAnd1998 currently running 0 too 0.06% with a spikenow and then, highest 2.2%. It started with 400ms.

**Comment by ChrisAnd1998** [comment]
I have released 1.4.4.0. I'ts also in submission for the store so it may take some time to be published. I hope that fixes the issue.

**Comment by Dragontech97** [comment]
Tested 1.4.4.0 and I can report similar numbers to what Crocodile73 saw with mostly average 0.2% cpu usage for explorer.exe with occasional spikes but nothing abnormal. Seems like the refresh rate was the issue! I guess I saw the bug on Windows Store version because the default setting was on 0. Thanks for the fix! If there are no other issues I can close this issue

**Comment by Dragontech97** [comment]
Quick question with the 1.4.5 update, currently FalconX idles at anywhere from 1-3% cpu usage, hovering around 2.2%. Is this within normal limits? Refresh rate is set to 400ms

**Comment by ChrisAnd1998** [comment]
With an Intel i7 4700HQ it should be dropping all the way to 0% or sometimes 0.1%. So thats still not normal and way to much 🤔. I also have an old gen i3 testing pc and it also drops to around 0.1% / 0.3% at idle. The idle state is when the taskbar doesn't move like most of the time.

**Comment by Dragontech97** [comment]
Very strange, I reverted to default settings as well and its around the same. 
![Screenshot (35)](https://user-images.githubusercontent.com/10717304/75809808-58b4c000-5d57-11ea-966a-83d59502b449.png)

**Comment by ChrisAnd1998** [comment]
Yep, this isn't right. The memory usage is also to much (normally about 4mb). It might be another application that is altering with FalconX that I don't know of.

**Comment by Dragontech97** [comment]
I do see brief periods where usage idles down to near 0% for both, but those last less than 2 seconds, and usage quickly goes back up to ~2% for me. I can increase refresh rate to 1000ms and can reduce it down further to 0.5% occasionally for both but it does seem that there is excess usage still. Exited every background app and window and left only FalconX and task manager running at 400ms and this is what I got, barely any difference and still far from what you experience on your end :( so there's more debugging I'll need to try. Let me know if you got any ideas!
![Screenshot (38)](https://user-images.githubusercontent.com/10717304/75812612-86503800-5d5c-11ea-9715-86b756c8bd4b.png)

**Comment by ChrisAnd1998** [comment]
Well, what you could try is this.
http://chrisandriessen.nl/web/img/2020-03-03%2021-04-30.mp4

The information that it gives doesn't really matter but, will show if it even goes into idle.
Just put the "FalconXOutput.exe" where you installed FalconX like i do in the video. Make sure to fully close any runnning instances of FalconX and then use "FalconXOutput.exe" to run FalconX with it's output. In the video you will also see how it should behave.

[FalconXOutput.zip](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4283352/FalconXOutput.zip)

**Comment by xiaozhe2333** [comment]
I also encountered the same problem as the subject, shcore.dll! The process occupancy rate of ordinal 172+0x100 is very high. I searched the website and found no solution, but suddenly found that the rule gave me a solution for my use scenario.

## Personal summary rules

1. When I open edge and chrome browsers, the occupancy of this process will soar

2. My computer is configured with a laptop plus an external display screen. I accidentally found that when the edge browser is displayed on the laptop screen with direct connection, the CPU occupancy rate is not so high, and when the edge browser is displayed on the extended screen with direct connection, and there is no maximum window, the CPU occupancy rate is also not high.

## Personal solutions

It was judged that there was a problem between the independent display and the system (I don't have much computer knowledge). However, the edge browser was not maximized on the expansion screen, which solved the problem of high CPU consumption

**Comment by xiaozhe2333** [comment]
I came here again, and found Microsoft's input method flashing all the time. This is it:
![image](https://user-images.githubusercontent.com/92240019/216815065-3d500804-ff48-4032-802a-173a57ed3d1a.png)
Is there a problem with the input method? Then set it and the problem disappeared. The specific steps are as follows:
![image](https://user-images.githubusercontent.com/92240019/216815058-a70187cf-9531-4487-ae6c-49d3618f5a4a.png)
![image](https://user-images.githubusercontent.com/92240019/216815033-bcf98eef-96a3-449d-bd8e-a6c7779c3372.png)
Turn this on and off to solve the problem
