### ISSUE TITLE
Autostart doesn't work 

### ISSUE THREAD

**Issue by arsonDev** [ChrisAnd1998/FalconX-Center-Taskbar#189]
Autostart with windows 10 not work correctly. Falcon worked after run FalconXSettings only

**Comment by ChrisAnd1998** [comment]
Are you using "Run at startup" or the "Task schedule" option ?

**Comment by arsonDev** [comment]
In version from MS Store I don't see "Run as startup" only "Task schedule"

**Comment by Duckrinium** [comment]
If issue applies to that, I can't remove FalconX from startup

**Comment by ChrisAnd1998** [comment]
The store version has no option to change that. When using the taskschedule option it will be disabled autmatically and vise versa. You can also open up task manager and enable/disable it from there.

**Comment by vsnst** [comment]
mine FalconX takes about a minute to start and 1sec for Transparent effect.

Desktop Customization software "Nexus" can somehow bypass windows restriction and open up very fast at startup, If FalconX can do that either that would be amazing.

**Comment by ChrisAnd1998** [comment]
@vsnst Did you use the taskschedule option?

**Comment by vsnst** [comment]
> @vsnst Did you use the taskschedule option?

No, I use task manager startup option, does that make any difference?

**Comment by ChrisAnd1998** [comment]
@vsnst Yes, it will then launch instantly when you logon ;)

**Comment by PUREHAX** [comment]
I want the taskbar transparent. Everytime I restart the pc I need to open the configurator and apply it again. How to change that ?

**Comment by PUREHAX** [comment]
Nvm. Just found out it workes like that : 
"D:\Program Files (x86)\TaskbarX.exe" -tbs=1

In autostart

**Comment by ChrisAnd1998** [comment]
In the Configurator you should hit the apply button. If that doesn't work then you need to increase the delay option of the taskschedule tab to like 10 or so.

**Comment by aenesks** [comment]
i am using 1.6.3.0 version. my taskbar icons are going through left and i cant reach them until restart the configrator and check "do't center" option. it reacts like there is a second screen but there isn't.

**Comment by SynixSherlock** [comment]
C:\Users\rabbi\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup 
paste the taskbarx.exe to this folder and restart

**Comment by AayushBoliya** [comment]
A shortcut is there, still doesn't start at startup

**Comment by DryreL** [comment]
Still don't start at launch. Purchased on Microsoft Store.

OS: Windows 10 21H2

**Comment by DevBySuraj** [comment]
just reset all settings to default and click on apply and restart your pc. Issue will be fixed.
