### ISSUE TITLE
High CPU usage on WIndows Explorer wrapper

### ISSUE THREAD

**Issue by CypherPotato** [ChrisAnd1998/FalconX-Center-Taskbar#193]
I'm getting like 14-16% CPU Usage on Windows Explorer process while Facon X is active. When I exit the app, the CPU usage returns back to normal. The Refresh Rate doens't change anything, even in 250ms or 2000ms.

I recorded a video showing the issue: https://youtu.be/gePDDzkt2tE

Now I'm aren't using the application since it are slowing down my system and games. I feel sad because I bought it from the Windows Store and this issue didn't happened before.

**Comment by ChrisAnd1998** [comment]
What version are you on? And is it the store version?

**Comment by ChrisAnd1998** [comment]
I just got the confirmation that it has been published ;)

**Comment by vsnst** [comment]
> I just got the confirmation that it has been published ;)

Just fixed my issue, Thank you so much, Chris :) 
![image](https://user-images.githubusercontent.com/36701269/75882051-50de4400-5e5b-11ea-89a1-5ccb92afc203.png)
