### ISSUE TITLE
Which .exe install choice?

### ISSUE THREAD

**Issue by chaloots** [ChrisAnd1998/FalconX-Center-Taskbar#202]
Had downloaded FalconX 02.03.2020 from Chris' site. Zip contains FalconX.exe and FalconXSettings.exe

Presumably the first is required for install. Is the second one also required?

P.S. Speaking of .exe files, I downloaded FalconX-Center-Taskbar-master from here on github and nowhere does it include an .exe file.

**Comment by ChrisAnd1998** [comment]
FalconX is the main application. If there are no settings it will go with the default settings. So FalconXSettings.exe is not really needed unless you want to change the settings. All dll files are required exept the "taskscheduler" one if you don't want to use the settings.
