### ISSUE TITLE
Can't buy on Microsoft store

### ISSUE THREAD

**Issue by mabasic** [ChrisAnd1998/FalconX-Center-Taskbar#204]
Just got the time to test your program, and it looks and works great! Congratulation!

I've opened this issue to let you know that I cannot buy the app on the Microsoft store. 

I get this message:

```
Try that again
Something happened on our end. Waiting a bit might help.
```

Maybe this is just me, but anyway wanted to let you know. 
Feel free to close this issue once you see it.

**Comment by dambler** [comment]
I literally just purchased it myself this morning through the MS store it and worked.

**Comment by mabasic** [comment]
After several unsuccessful attempts, I've tried again just now and it worked.
