### ISSUE TITLE
[Query]FalconX- Free vs Paid

### ISSUE THREAD

**Issue by onlytanmoy** [ChrisAnd1998/FalconX-Center-Taskbar#206]
Please explain me the difference between the free zip version and the paid version from MS Store.

**Comment by ChrisAnd1998** [comment]
The store version is exactly the same as the normal/free version. It's a donation sytem. The store version does give you the benefit of automatic updates and easy installing.

**Comment by onlytanmoy** [comment]
Thanks for the prompt response and clarification Chris. I will go for the paid store version as I really like your app 👌
Do you already have 'Genie minimization effect' as one of the included animations?
As you might know the Genie effect is what all Macs do by default. Whenever you minimize a window, the window gets skinny at the bottom and gets 'sucked into' the dock. Let me know.

**Comment by ChrisAnd1998** [comment]
Thx 😁,

I'll look into it. 
Would be a hard one to achieve but, I'll give it a try 😉

**Comment by onlytanmoy** [comment]
Super, I just completed the purchase. I will create a new GH issue as feature request on this.

**Comment by ChrisAnd1998** [comment]
Thx! Allright 👍
