### ISSUE TITLE
[Feature Request] Make pinned, but closed apps stay on the left.

### ISSUE THREAD

**Issue by CuraeL** [ChrisAnd1998/FalconX-Center-Taskbar#208]
Great app. Been looking for this for a while. I love it, I am old school and prefer my apps to be expanded with text and never grouped. The only thing I don't like is that my pinned apps follow along with what's "open" in the taskbar. I'd love to see an option to undo this so that everything that's just pinned, but not open, stays to the left, along with search and all that other Windows 10 gunk. :)

Thanks for a great application. It really raises the aesthetic of Windows! And it just works!

**Comment by ChrisAnd1998** [comment]
Would be hard to archieve as i don't have control on the icons sepperatly. I can get their size, position etc.. but, can't move them :/ 

I'll give it a try ;)

**Comment by CuraeL** [comment]
Oh, yeah, I imagined there'd be those kinds of limitations. I suspect it will be a trouble to try and circumvent.
As you just created that new pin message as I got done; Good luck on optimizing the whole thing! I hope it works out! I feel like it already works really well.

**Comment by ChrisAnd1998** [comment]
Thx, i will just try it but, i can't promise anything ;)
FalconX works on 9/10 of users. I want it to be perfect.

**Comment by ChrisAnd1998** [comment]
I'm sorry to disappoint you but, i can't get them separated i think it's just not possible :(
