### ISSUE TITLE
Transparent only on desktop mode

### ISSUE THREAD

**Issue by William-at-github** [ChrisAnd1998/FalconX-Center-Taskbar#212]
Hi Chris,

I'm wondering that if Falconx could add a option to make taskbar transparent only on desktop mode, since it will be a little distractive if we work in maximal windows with totally transparent taskbar.

Thank you!

**Comment by ChrisAnd1998** [comment]
That would be possible. I have to look how TranslucentTB does this.
Currently i am focussing on the complete rewrite of FalconX. When i finish the rewrite i will look into new feature requests like these ;)

I will close this issue because it has already been requested in issue #149
