### ISSUE TITLE
Taskbar flickering [TaskbarX]

### ISSUE THREAD

**Issue by Dolneaz** [ChrisAnd1998/FalconX-Center-Taskbar#216]
On Build v14 and v15 i had massive flickering (Normal Taskbar <-> Blur Effect) when running with following Parameters "-taskbarstyle=2 -looprefreshrate=1000 -fixtoolbarsontraychange=1 " on a 3 Monitor Setup.

**Comment by ChrisAnd1998** [comment]
Hmm, can you see if it's restarting multiple times using Taskmanager?

**Comment by Dolneaz** [comment]
Sure thing. Wait i cant XD Forgot to say that it only happens if no application is opened!

**Comment by Dolneaz** [comment]
What i can tell is that an old Version of TaskbarX works just fine under the same conditions. I think my current is V12 or v13

**Comment by Dolneaz** [comment]
Okey. I did a lot of Testing:
- Version 14 and 15 always flicker if Taskbar Style != Default and not Window is active/on the tray
- No Combination of Configurations can prevent the flickering
- The Update interval has an impact on the time until the first flickering occures after the last window was closed. (Not on the ones that follow cause the process indeed restarts all the time and loses configuration in that process vgl. Process Hacker Log)

[Process Hacker Log.txt](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/files/4453480/Process.Hacker.Log.txt)

I really hope this will help you to fix the issue cause i really really like this project. Keep up the good work :-)

**Comment by ChrisAnd1998** [comment]
Thanks for the details 😁👍. I will look into it. 
In v14 the application restarts when any error occurred v13 and lower will just continue running.

I'll let you know if i think i got a fix 😉

**Comment by ChrisAnd1998** [comment]
Allright!

Your log file explained what i predicted was happening. It was indeed constantly restarting.
That pointed me to the right block of code :).

When i closed all icons from my taskbar as you said i was able to reproduce the issue.

So **v16** should fix the issue ;)
