### ISSUE TITLE
[wish] Hide Trayicon

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/FalconX-Center-Taskbar#23]
Ich fände es klasse, wenn man optional das Trayicon ausblenden könnte. Sprich die Optionen über eie Verknüpfung oder das wiederholte starten der Anwendung hervorruft. Die Einstellung verwendet man in der Regel  nicht so oft, sodass ein TrayIcon gelegentlich überflüssig ist und bei vielen anwendungen die im Tray-Liegen mehr überblig schaffen.
Die Funktion wünsch ich mir optional.

**Comment by ChrisAnd1998** [comment]
I will think about it... i have marked it as an enhancement for now.

**Comment by leminsc8er** [comment]
i think it will better without this wish!

**Comment by ChrisAnd1998** [comment]
Yes, i don't want to make this wish happen because, i tried doing so but, resulted in permission issues when running from the Windows Store.
