### ISSUE TITLE
Taskbar Icons dont center on additional monitors when Windows Display 1 isn't Main Display.

### ISSUE THREAD

**Issue by v-rogg** [ChrisAnd1998/FalconX-Center-Taskbar#32]
When Windows Display 1 is configured as Main Display, the taskbar icons get centered.
When any other Display is configured as Main Display, only the Main Display's taskbar icons get centered.
I can confirm this issue for using two and three monitors.

Running:
- FalconX 1.2.6.0
- Windows 1903

After a bit of testing and multiple restarts (FalconX and Explorer) I get it to center at start, but after a few moments I get the same issue as in issue #31 or it stops working all together.

**Comment by v-rogg** [comment]
Ok, now suddenly it works.
Im going to further test this issue. During the day at work (3 Monitors) I couldn't get it to center. At home (2 Monitors) it worked after multiple times switching my main display. Im using the same computer.

**Comment by ChrisAnd1998** [comment]
Thanks for the confirmation but, i have not been able to reproduce this on my own pc and not on my testing pc's. I personally have a tripple monitor setup with the second monitor as my main display. And some testing pc's have a dual monitor setup.

Can you put this confirmation under issue #31 ? So there won't be issue duplicates.
