### ISSUE TITLE
Req: Add Fluent/Blur style transparency options.

### ISSUE THREAD

**Issue by swsegdan** [ChrisAnd1998/FalconX-Center-Taskbar#34]
I've personally always found straight up 100% transparent to look slightly odd when you've got windows maximized. Having the option to set it as 'Fluent' or smilar would be neat.

**Comment by ChrisAnd1998** [comment]
Allright, i have added them ;)
Acrylic / Fluent need some tuning though... (it can flicker a little sometimes)

**Comment by QkeleQ10** [comment]
@ChrisAnd1998 Hi, the Acrylic style doesn't seem to be working for me.
![image](https://user-images.githubusercontent.com/55982900/74524988-62998f00-4f20-11ea-9cbe-e1b15093f4ba.png)

**Comment by ChrisAnd1998** [comment]
@QkeleQ10 Well, yes it's not a very stable style. It sometimes works and sometimes doesn't. I'm still doing research to apply styles to the taskbar in a different approach than how it's done now like every other taskbar styling tool does.

So i basically can't do anything about it right now but, i may find a better way to do it in the future.

**Comment by QkeleQ10** [comment]
Okay, I completely understand.

[Quinten Althues](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=dobdl)	[dobdl]

Met vriendelijke groet,
Quinten Althues

On February 14, 2020 at 11:17 GMT, Chris Andriessen <notifications@github.com> wrote:

[@QkeleQ10](https://github.com/QkeleQ10) Well, yes it's not a very stable style. It sometimes works and sometimes doesn't. I'm still doing research to apply styles to the taskbar in a different approach than how it's done now like every other taskbar styling tool does.

So i basically can't do anything about it right now but, i may find a better way to do it in the future.
