### ISSUE TITLE
Icons don't center correctly

### ISSUE THREAD

**Issue by Lukas34** [ChrisAnd1998/FalconX-Center-Taskbar#36]
I'm running the Microsoft Store version and I got updated to the newest version 1.2.8.0 today. Now all my taskbar icons are shifted way too much to the right and the center-checkbox in the menu does not do much.  Here is a screenshot:

![image](https://user-images.githubusercontent.com/36658128/67273046-fea91180-f4bd-11e9-8f81-04e5593c962e.png)

I've tried uninstalling and downloading it again as well as using the regular .exe from GitHub Releases as well as restarting my PC.

I am running Windows 10 Pro 1903 (Build 18362.418) and I am only using one monitor. I have Spacedesk Server (allows you to use tablet or phone as second display) installed but not in use and also tried stopping it but that did not help. I also have Wallpaper Engine and TranslucentTB installed but I also closed those and it had no effect.

**Comment by silencesys** [comment]
Check settings (rclick on the icon in taskbar) if there is 0 in `Offset position in pixels`. I had similar issue and there was 500px offset, so I removed it and everything works fine again.

**Comment by Lukas34** [comment]
Ah yes, thanks. I totally overlooked that option.
