### ISSUE TITLE
Icons cant find center after update and continue to try and move to the right side of task bar

### ISSUE THREAD

**Issue by Zambzz** [ChrisAnd1998/FalconX-Center-Taskbar#37]
I had my icons centered on the task bar and the newest update has made them want to align right side which also obscures some of my icons.

I have tried restarting app and windows and have yet no luck.

**Comment by Lukas34** [comment]
Had the same problem after the update. If your problem looks like #36 you just need to adjust the offset position to 0.

**Comment by Zambzz** [comment]
yeah that worked for me, didn't see #36
