### ISSUE TITLE
Causes windows explorer and the windows shell to crash

### ISSUE THREAD

**Issue by johneusebio** [ChrisAnd1998/FalconX-Center-Taskbar#38]
I'm running FalconX on my Surface Book 2 and it occasionally causes my Windows taskbar to crash. The taskbar becomes unresponsive, eventually prompts me to End Process (stating Microsoft Windows has crashed), and then it appears that my entire Windows shell ends. Sometimes the Windows shell restarts after a few minutes, but other times I need to force my computer to shut down.

I'm using the Windows Store version, and my windows version OS Build 18362.418.

**Comment by ChrisAnd1998** [comment]
Sorry for the late response but, does this still happen with 1.3.3.0? There have been some changes lately.
Also this can only happen if something else is doing something with the taskbar to.

Store Version is at 1.3.2.0 atm. Version 1.3.3.0 will be submitted within a couple days.
