### ISSUE TITLE
Save the configuration file in the same folder

### ISSUE THREAD

**Issue by maboroshin** [ChrisAnd1998/FalconX-Center-Taskbar#39]
For Developer.
I want to save the configuration file in the same folder as the program.
Not the My Documents folder.

**Comment by ChrisAnd1998** [comment]
The config will now be saved in your Appdata.

I can't save it in the install directory because, then i have no permission to modify and read it when
you use the Windows Store version.

**Comment by maboroshin** [comment]
I understand the permissions.
Thank you for the alternative solution. 😊
