### ISSUE TITLE
Offset not applying until manual refresh

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#44]
I understand a refresh is probably needed for a offset value change to take effect. Could the reresh be made automatically when OK button is pressed? (Because you would usually expect OK button to apply the changes without any other actions needed.)

**Comment by ChrisAnd1998** [comment]
Well, it should refresh automatically when you hit enter or when you click somewhere else (it's a bad feature from the numeric up down control). I am thinking of switching back to regular textboxes because then i can refresh it on keydown.

**Comment by Martin5001** [comment]
Regular textbox would be fine in my opinion because I never got used to clicking the arrows so I type anyway and it is usually faster for bigger numbers to just type them.

**Comment by Martin5001** [comment]
Or maybe a slider would be even better option, at least from a visual perspective.

**Comment by ChrisAnd1998** [comment]
That could also be a nice one but, also needs something to see the actual value. I will try to get something visually good and more functional for the next update.
