### ISSUE TITLE
Transparency not working for a moment when clicking on start

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#46]
If I set taskbar to transparent, then it blinks for a second whenever I open or close Start.

**Comment by ChrisAnd1998** [comment]
Hi Martin,

Can you see if this testing build fixes the issue. I don't see it happening on mine anymore but, want to make sure.

https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by Martin5001** [comment]
Hi Chris,

yes it seems like it works fine now.

**Comment by ChrisAnd1998** [comment]
Wow you're fast XD.
Thanks for testing it, i'll keep it running to see if it comes back but, so far so good :)

**Comment by Martin5001** [comment]
XD
