### ISSUE TITLE
Taskbar centered regardless of the settings

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#47]
Taskbar does not get back to normal left alignment after unchecking the center option. It moves slightly off to the right hovewer. When I exit Falcon completely, the taskbar gets back to normal.
I have used version 1.2.8, 1.2.9 (testing) and now I am on 1.2.9 (latest build from 27th), maybe the settings from the older versions might have remained active?

**Comment by ChrisAnd1998** [comment]
But there isn't a "center option" right? 

Or do you mean the "center between option" ?
If so then it should center between the start button, search etc... and your right tray menu on the right with your clock, volume etc... When you uncheck it then it should move back to the center of your screen.

**Comment by ChrisAnd1998** [comment]
Thanks for opening all the issues. It helps me alot making FalconX better. 😁👍

**Comment by Martin5001** [comment]
Yes, I ment this. Thanks for your explanation.
