### ISSUE TITLE
idea/tip: Consider using Electron for Settings UI

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#50]
Have you ever thought about using [Electron](https://electronjs.org/) or React?
Don´t know how familiar with webdesign you are but if you are then it could help to **solve the sizing problem you mentioned at issue #18** because you can use CSS stylesheets. Also you can easily change the size of the elements based on if the user is using touch screen laptop ([so bigger UI elements are needed to make touch control comfortable](https://css-tricks.com/touch-devices-not-judged-size/)) or just a regular desktop. Recently, CSS added support for [detecting the desired color theme (light/dark)](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) based on system settings.
Another advantage is that it is a good choice for a Windows Store version too (Skype UI is made using React for example.)
And these are just some examples, there is much more.
Hope this will be helpful.

**Comment by ChrisAnd1998** [comment]
Well i have thought about it but, FalconX needs to keep it's CPU Usage as low as possible. With Electron this increases a lot. The second problem is that i can't use the UI Automation API with Electron. However this can be solved to make a gui and a background service sepperatly but, then i will get permission issues with the store version. (In the store version you have no permission in the install directory).

Thanks for giving the idea 👍 but, this one sadly is a no go :(
