### ISSUE TITLE
Settings UI small visual tweaks

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#53]
I am now on the testing build. Thank you for adding the tray context menu there. I have one more suggestion related to this: As Falcon is a taskbar utility it would look nice if the tray context menu used the same style as Windows taskbar context menu itself. It could look like this:
![context_menu](https://user-images.githubusercontent.com/35201200/67752578-7e415e00-fa33-11e9-8c24-d139a9e0952a.png)
Maybe [this](https://stackoverflow.com/questions/32786250/windows-10-styled-contextmenustrip) and [this](https://stackoverflow.com/questions/32266658/visual-studio-2015-context-menu-system-style) could help?
(Btw. I think the settings icon is built into Windows 10 as a font.)
__________________________
Another idea: Maybe you could add one more label to divide Settings as "Animation options" (animation and animation speed), "Position options" (offsets and center between start checkbox) and "Taskbar style options" (as is now). I think this would make the UI easier to navigate.
__________________________
Yet another: Maybe moving the animation time and offset position units after the textbox may look slightly cleaner as making the label shorter and thus easier to read. And it could potentionally help in localization process as well. Could look like this:
![settings-values-units](https://user-images.githubusercontent.com/35201200/67755865-3d4c4800-fa39-11e9-83dc-9d51027276f3.png)
__________________________

(Also you made a small typo in Transparent - "Transparant" :) but that´s not so important.)

Hope it doesn´t matter that I am posting more ideas in one thread, but these are just too small to have their own issues :)

**Comment by ChrisAnd1998** [comment]
No problem! i am just very happy you can point so much out :). I am currently trying to get every possible idea and fixes ready for update 1.3.0.0.

**Comment by Martin5001** [comment]
I'm glad I can help.
