### ISSUE TITLE
Animation triggers twice

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#54]
The centering animation (on "Center between..." toggle change or on startup when moving from left to center) is triggered but does not finish fluently and starts again, so it triggers twice. This occured on all versions I used (at least from 1.2.8.0 to 1.3.0.0, maybe even older but not tested).

**Comment by ChrisAnd1998** [comment]
Yeah... i noticed that one to but, i did not take it as a priority. I will try to do something about it ;)
