### ISSUE TITLE
Config file should probably contain value names (using JSON?)

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#55]
This is not something really crucial but I think config file should contain not just values but also names of the property being set. This way it wouldn´t matter in which order the entries are written.
(I was just curious what happens if I mess with the config file a little bit so I came up with this idea after.) Using something like JSON might be a good way to do this.

This could allow for example setting the app automatically by changing the config via command prompt. (I am thinking about this beacuse I may want to create a bundle with some other software and set it up automatically to use it on my other computers or when I do a factory reset etc. But I mean that **for my personal use only**.) Also it would be beneficial in case you add something in the future, then the old settings would remain valid and the only thing needed to be set would be the new entry added.

**Comment by ChrisAnd1998** [comment]
Currently iam rewiting FalconX. To prevent any issues with settings not saving or reading. It will now use commandline parameters. This may also be a solution to what you are trying to archieve ;)

https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/releases/tag/1.5.0.0
