### ISSUE TITLE
Update check improvements

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#56]
Having an option to check for testing releases would be nice. Could look like this:
![update](https://user-images.githubusercontent.com/35201200/67843282-fd01ce00-fafb-11e9-9f58-103cd6b5b182.png)

Also the website with download should not open when user closes the window but only when clicked OK, so they can decide to update later.

Also it would be really convenient if the update installed automatically, but that would be more work for sure. Maybe using [ClickOnce](https://docs.microsoft.com/cs-cz/dotnet/framework/winforms/clickonce-deployment-for-windows-forms) deployment could make it easier. Anyway, it´s good already.

**Comment by ChrisAnd1998** [comment]
Thats a good one :)
