### ISSUE TITLE
Update check error

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#57]
I got this error when clicking Check for updates (then when I clicked End in that error dialog, it ended the tray but Falcon kept running, so there was no standard way of exiting the app or opening the settings as tray was not there - so maybe when an error happens in tray code, it should either end Falcon itself too or restart the tray automatically):

> ************** Text výjimky **************
System.Net.WebException: Vzdálený název nelze rozpoznat: 'chrisandriessen.nl'
   in System.Net.WebClient.OpenRead(Uri address)
   in System.Net.WebClient.OpenRead(String address)
   in FalconX4.Gui.CheckForUpdatesToolStripMenuItem_Click(Object sender, EventArgs e)
   in System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   in System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   in System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   in System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   in System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   in System.Windows.Forms.ToolStrip.WndProc(Message& m)
   in System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Načtená sestavení **************
mscorlib
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

FalconX
    Verze sestavení: 1.3.0.0
    Verze Win32: 1.3.0.0
    Základ kódu (CodeBase): file:///C:/Users/marti/Downloads/Test%201.3.0.0%20v1/FalconX.exe

Microsoft.VisualBasic
    Verze sestavení: 10.0.0.0
    Verze Win32: 14.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll

System
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Core
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Windows.Forms
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Runtime.Remoting
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll

UIAComWrapperX
    Verze sestavení: 1.1.0.16
    Verze Win32: 1.1.0.16
    Základ kódu (CodeBase): file:///C:/Users/marti/Downloads/Test%201.3.0.0%20v1/UIAComWrapperX.DLL

Interop.UIAutomationClient
    Verze sestavení: 12.0.21213.0
    Verze Win32: 12.0.21213.0
    Základ kódu (CodeBase): file:///C:/Users/marti/Downloads/Test%201.3.0.0%20v1/Interop.UIAutomationClient.DLL

WindowsBase
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll

Accessibility
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

mscorlib.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/mscorlib.resources.dll

System.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.resources.dll

System.Windows.Forms.resources
    Verze sestavení: 4.0.0.0
    Verze Win32: 4.8.3921.0 built by: NET48REL1
    Základ kódu (CodeBase): file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_cs_b77a5c561934e089/System.Windows.Forms.resources.dll

**Comment by ChrisAnd1998** [comment]
hmm, i think it failed to access to txt file on my webhost.
