### ISSUE TITLE
Using tray when Settings opened freezes Settings window

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#58]
When I open Settings and then click Check for updates in tray while Settings window is still opened, it does not open the update dialog and the Settings window freezes (while it seems to be responding to the system ("Not responfing" is not shown), just can´t click anything.)
The Exit button in the tray works though.

**Comment by ChrisAnd1998** [comment]
Because to Settings window is topmost. I can fix that.
