### ISSUE TITLE
Some more UI related tips

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#60]
Thank you very much for implementing some of my previous ideas so qickly in 1.3.0.0 :) . I have some more UI related suggestions (really minor things though).
_______________________________
**Settings icon**
The settings icon in tray menu should be centered - moved more to the right.
![Bez názvu](https://user-images.githubusercontent.com/35201200/68019025-df1e9f80-fc9a-11e9-9c38-8208488b4f9a.png)
________________________________
**Spacing**
Also adding some more margin to the top and the bottom of the context menu to give it a little more space would look nice, I think. (So the spacing between items and the spacing on top and bottom of the menu would be the same - as marked.)
![Bez názvu](https://user-images.githubusercontent.com/35201200/68019862-26a62b00-fc9d-11e9-8d41-8f0f08f5b742.png)
__________________________________
**Typography**
I think using Seoge UI instead of Tahoma would be good as it is Windows default system font (recommended in ms [docs](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-fonts)). (Seoge fonts are built into windows since Vista, so compatibility is no problem.)

Also in my opinion the combobox and the values textbox in Settings should not be bold because it is not a title. I would use regular font in the tray context menu as well because bold is not needed there as it is already separated by the line.

**Comment by ChrisAnd1998** [comment]
Well i liked the idea but, i have now separated the settings window from FalconX. So there is no need for a tray menu anymore :)
