### ISSUE TITLE
Taskbar styling options not working until refresh

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#61]
When I change Taskbar styling options, it does not update until refresh. Previously (I think 1.3.0.0 testing build) it showed the changes immediately (without need to press OK) but now (1.3.0.0 public release) it does not apply them even after pressing OK, only on refresh/rerun or when I uncheck and check "Enable taskbar styling" checkbox.

**Comment by ChrisAnd1998** [comment]
I also can't reproduce this on my desktop or laptop :(
