### ISSUE TITLE
Bugs with toolbar from NetspeedMonitor

### ISSUE THREAD

**Issue by semool** [ChrisAnd1998/FalconX-Center-Taskbar#65]
I know NetspeedMonitor is a really old Addon, but it works fine.
When the toolbar is enabled and placed left to the systemtray and i start FalconX als is fine and working.
But by a change in the SystemTray, a new icon or a disapperring icon the netspeedmonitor toolbar stay on its place. So the icons overlapp the toolbar or an interspace arises.
Then i must open FalconX and click on refresh and all is again in place.

**Comment by ChrisAnd1998** [comment]
Hmm i see, have reproduced to bug but, i have to enable the taskbar's redraw to fix this.
if i enable the taskbar's redraw then the taskbar icons will move back to the left every now and then. It also brings back a very annoying flickering bug.

So for now i don't know another way to fix this but, i will continue experimenting to find a proper fix.

**Comment by semool** [comment]
Thank you, your App is great but i cant live without NeetSpeedMonitor :)

**Comment by ChrisAnd1998** [comment]
I will close this to prevent duplicate issues. #96
