### ISSUE TITLE
Older version check

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#66]
When I check for updates it says version 1.3.0.0 is latest but I am already running 1.3.1.0. The app should check for this condition.

```
(Gui.vb / Line 359)

If latest <= Application.ProductVersion Then
                MessageBox.Show("You are up to date!")
            Else
...
```

**Comment by ChrisAnd1998** [comment]
Woops, sorry i forget to update the version file. It should be fixed now ;)
