### ISSUE TITLE
Settings window showing black squares when going from minimized state

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#69]
When I minimize the Settings and then show it again, it takes some time for it to load so it shows black squares in place of controls for a moment. (I suspect this has something to do with it not being topmost anymore?)

**Comment by ChrisAnd1998** [comment]
Idk, i will look into it :)

**Comment by ChrisAnd1998** [comment]
I have now seperated the settings window from FalconX in update 1.3.6.0.
So it may not happen anymore.
