### ISSUE TITLE
Language/grammar related suggestion

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#70]
**Capital letters in the middle of a word (teacher approved)**
Of course I am not a native English speaker, but I´ve asked my English teacher who said that it is not correct to use capital letters in the middle of a word - as in UnStable and StartUp.
__________________________________________
**Title case (Written Like This) vs. sentence case (Written like this) (my opinion only)**
Also I noticed that Windows does not use capital letters for control labels (but does so for titles) like on this picture from Mouse settings where "Pointer Options" as a title of a category/group use title case, but the labels, like "Enhance pointer precision" use regular/sentence case. So I think it is generally a good practise to match this style as people are used to it.

That would mean to **use title case on group labels/titles** like Animation Options, Position Options, etc., **but use sentence case on individual controls** labels like Animation speed, Enable taskbar styling, Report bug, etc.

![Windows Mouse settings window](https://www.eliteownage.com/images/mouse/windowsmousesettings.png)

**Comment by ChrisAnd1998** [comment]
Very nice that you even asked your English teacher 👍.

Personally i only know the basics of English grammar. 
And saw that everyone uses it differently so, i used the capitals for the important words and just what looks best. Your teacher just confirmed that it's not correct to use capitals like that so i will definitely change that. I will also look how Windows uses the capitals like in your screenshot to make it more even.
