### ISSUE TITLE
Taskbar icons cropped and not centered when going from multi monitor to single

### ISSUE THREAD

**Issue by JefRH1** [ChrisAnd1998/FalconX-Center-Taskbar#71]
On a Surface book 2 with dock.  I have 2 monitors connected.  Book is at 3240x2160 @ 200%.  External monitors are both at 2560x1440 @ 100%.

When I disconnect the dock, my icons will be left aligned and cropped.  If I reconnect, the icons are no longer cropped, but they are still left aligned.

![TaskbarCrop](https://user-images.githubusercontent.com/2340031/68865269-299b1580-06b8-11ea-9490-cb72023afe2b.jpg)

**Comment by JefRH1** [comment]
Sometimes it does center, but is still cropped.  Clicking the Refresh button seems to fix it.

**Comment by ChrisAnd1998** [comment]
Since FalconX now restarts when the total resolution changed this should'nt be happening any more right?
