### ISSUE TITLE
Dual Monitor issues

### ISSUE THREAD

**Issue by cequence** [ChrisAnd1998/FalconX-Center-Taskbar#73]
I always install and reinstall because of issues with dual monitor, at first it works fine but after a little the non-primary monitor is no longer transparent. Also center task bar bounces around as if its lagging.

**Comment by Sn0wCrack** [comment]
I'm having similar issue in my multi-monitor setup.

It appears every time I lock my computer (or it goes into sleep mode and I need to unlock it again), the taskbar on every monitor except my Primary monitor, reverts back to a solid taskbar that has the same colour as my selected accent colour.

**Comment by Spagoot420** [comment]
It seems like I have the exact same issue as Sn0wCrack...

**Comment by Sn0wCrack** [comment]
After the v1.3.4.0 update this issue no longer appears to occur

**Comment by apolios** [comment]
1.3.4.0 and still issues:

a)
1. When start system with one monitor active all is ok.
2. win + P -> extend = second monitor not centered, not transparent and app settings doesnt respond. Have to kill proccess and rerun app.

b)
1. When start system with dual monitors active all ok.
2. Changing to primary only or others causes same bugs.

**Comment by isc30** [comment]
With 1.3.5.0 the bug still happens as described by @apolios

**Comment by ChrisAnd1998** [comment]
Confirmed in issue #91. This will be closed due to duplicate issues.
