### ISSUE TITLE
I don't have credit/debit card or paypal.

### ISSUE THREAD

**Issue by armaninyow** [ChrisAnd1998/FalconX-Center-Taskbar#74]
I wanted to buy and install falconx on microsoft store but I don't have credit/debit card or paypal. And unfortunately, the "via mobile phone" method of purchasing is not available in the philippines.

Is there any other way to donate to you and give me a gift code instead?

**Comment by ChrisAnd1998** [comment]
I really appreciate you want to buy the store version but, the only way for me would be Paypal.
