### ISSUE TITLE
Disconnecting one monitor causes FalconX to freeze.

### ISSUE THREAD

**Issue by Dansel** [ChrisAnd1998/FalconX-Center-Taskbar#75]
Note: I've only tested this when you're starting with multiple monitors.

Fairly simple to reproduce:
1. Start FalconX
2. Turn off monitor or unplug cable

Now the GUI is entirely frozen. The software still works on the monitors then were never disconnected, but it won't detect the reconnected one and is, as mentioned, frozen.

Win 10 1909, FalconX 1.3.2.0 

Edit: Also, version 1.2.7.0 keeps working when you've disconnected a monitor. You have to restart it to rediscover the reconnected monitor, but it's easy to do that with the button in the GUI.

**Comment by ChrisAnd1998** [comment]
FalconX will auto restart when a monitor gets unplugged next update.

**Comment by swsegdan** [comment]
I'm still getting this issue on the new version if the computer is asleep when the disconnect happens.

**Comment by ChrisAnd1998** [comment]
@swsegdan 1.3.3.0 caused big crashing issues. So i had to roll-back to 1.3.2.0. I will reapply this fix for from 1.3.3.0 for 1.3.5.0.
