### ISSUE TITLE
Taskbar in secondary screen is blue

### ISSUE THREAD

**Issue by tuannv1804** [ChrisAnd1998/FalconX-Center-Taskbar#88]
When i locked my computer and loged in after. Secondary screen's taskbar was changed blue. And i must apply setting again. Please fix it. Thanks!

![image](https://user-images.githubusercontent.com/45984386/69698590-51f32d00-1118-11ea-80f7-b9518c0e8d5f.png)

**Comment by Dylox** [comment]
Same for me, except mine turns red as that's my theme color. I've added my FalconX settings just in case. Other than that, I really love FalconX so thanks!
![2019-11-29 13_56_48-FalconX](https://user-images.githubusercontent.com/58333669/69870459-37ec5280-12b0-11ea-8158-24fd37a44612.jpg)
