### ISSUE TITLE
Taskbar stuttering to get back

### ISSUE THREAD

**Issue by abhishek28069** [ChrisAnd1998/FalconX-Center-Taskbar#89]
In some animation modes the taskbar is constantly adjusting itself to a position even though the number of applications opened is constant.

**Comment by KuzonCode** [comment]
I am also having this issue.

**Comment by ChrisAnd1998** [comment]
Is this what you are experiencing?

Taskbar icons continuously moving [#30](https://github.com/ChrisAnd1998/FalconX-Center-Taskbar/issues/30)

**Comment by abhishek28069** [comment]
yes it is....

**Comment by ChrisAnd1998** [comment]
Thanks, then i will close this issue to avoid duplicate issues ;)
