### ISSUE TITLE
📌 | 🎅🎄😓 Slow or maybe even no updates for December. 😓🎄🎅

### ISSUE THREAD

**Issue by ChrisAnd1998** [ChrisAnd1998/FalconX-Center-Taskbar#90]
I just wanted to let you all know i am very busy these last weeks of 2019, finishing everything up on my primary business before the new year. So i sadly have no time left atm for FalconX. 
I hope you all understand 😁. 

I will definitely be actively updating and fixing FalconX again from January 2020!
Feel free to open new issues!

**_I wish you all a very happy christmas and a happy new year! 🎆🎄🎅_**

**Comment by Cabola** [comment]
Merry Christmas and happy new years to you too!
