### ISSUE TITLE
1.3.3.0 Starting and stopping

### ISSUE THREAD

**Issue by lwetzel1** [ChrisAnd1998/FalconX-Center-Taskbar#93]
This version will startup and then disappear from the Taskbar only to startup and disappear.  It can be stopped if you catch it as it reappears on the taskbar by right click -> exit.  I have reverted back to version 1.3.2.0 until fixed.

**Comment by ChrisAnd1998** [comment]
You mean that is shows the gui/form and its icon in the taskbar for 1 second.
Only when you launch FalconX?

If so, i noticed it too and will be fixed in 1.3.4.0 ;)

**Comment by lwetzel1** [comment]
Yes pretty much.  When the app is started it puts the icon up and flashes a window on screen and then both disappear.  It will repeat it continuously until I catch it just as it appears in the taskbar, right click it and click exit.  I have seen it on two machines and both the Windows store version and the version downloaded from you site.  Like I said I reverted to the version before this one and wait for you next.  I know you are busy with end of year so assume it will be early 2020.

Thanks!



Lew Wetzel

**Comment by Lisser** [comment]
+1! 🙂

**Comment by AndersonALAC** [comment]
Same issue, the window flashes whenever the taskbar changes to or from empty. In other words, it appears when a first window opens or a last window closes

**Comment by lwetzel1** [comment]
@AndersonALAC 

That doesn't sound like the issue I am seeing.  When you start the application the icon shows up and a window opens and immediately closes and the icon disappears. Then it just repeats until you catch the icon and right click to exit.

**Comment by Cabola** [comment]
yup same issue for me with 1.3.3.0 it starts then crashes then starts then crashes until it finally crashes completely. Everything the icon down by the clock appears and the main window shows up only to close 1 sec later.

**Comment by ChrisAnd1998** [comment]
Should be fixed now ;)

**Comment by lwetzel1** [comment]
Yes it appears to be working in this version.

Thanks!
