### ISSUE TITLE
Center only the icons on the primary taskbar

### ISSUE THREAD

**Issue by convalise** [ChrisAnd1998/FalconX-Center-Taskbar#94]
Please add an option to center only the icons on the primary taskbar, ignoring other taskbars/monitors. Maybe a checkbox in settings?

EDIT: I just saw the old versions had the option "center on multiple monitors" but it was removed. The "refresh rate in millisecond" option is gone too. Any chance they will come back? I'd like to disable the multi-monitor feature and configure a refresh rate on 100 or lower (despite CPU usage warning).

**Comment by Cabola** [comment]
This is actually happening to me in the latest version. It's only my primary monitor that centers the icons, my 2 other monitors stays default. :/

**Comment by ChrisAnd1998** [comment]
Added in 1.3.6.0
