### ISSUE TITLE
NetspeedMonitor doesn't stick to tray

### ISSUE THREAD

**Issue by rainonline** [ChrisAnd1998/FalconX-Center-Taskbar#96]
**before**
![unuse](https://user-images.githubusercontent.com/16534596/70225143-7179fd80-1789-11ea-9d0e-57bf76f87167.gif)
**after**
![use](https://user-images.githubusercontent.com/16534596/70225153-78a10b80-1789-11ea-937e-6e159986b918.gif)

**Comment by Cabola** [comment]
I never paid attention to it, but I see this happening to me too! Does it in 1.3.2.0

**Comment by ChrisAnd1998** [comment]
Well this has been reported before @ #65 

But sadly there isn't something i can do about this issue.
FalconX disables the taskbars redraw to prevent the icons from flickering back and forth.
If i enable the redraw it will fix this issue but, will reopen the most annoying bug (flickering back and forth). 

I will keep this issue open in case i find another way to fix this.

**Comment by Cabola** [comment]
For me it's just the normal toolbars that it does it to. I have a "HP support assistant quick access" icon that it does it to. I don't have the NetspeedMonitor thing..

**Comment by Martin5001** [comment]
@ChrisAnd1998 Could this be solved by checking how many apps are shown in tray and refreshing the taskbar only if that number changes?
I found some [discussion here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/4c4f60ce-3573-433d-994e-9c17f95187f0/finding-which-applications-and-services-are-listed-in-the-system-tray?forum=csharpgeneral) but it´s in C# so I don´t know if it could be rewritten to VB.

**Comment by ChrisAnd1998** [comment]
@Martin5001 Yes, it is possible to enable the redraw of the taskbar when the tray changed. But then i also need to refresh the taskbar to make it adjust itself. When i then refresh the taskbar the taskbar toolbar will be at the right position but, the taskbar icons will jump to the left.

I will have to do more testing on this.

**Comment by Cabola** [comment]
I don't believe it's another software at fault, unless that software is Windows 10. It's the actual "toolbars" in the task bar that has the issue. If you right click the taskbar and go into Toolbars and select "New toolbar...." then select a folder, it should add that folders name along with 2 arrows next to it onto the taskbar. You probably have to close down and relaunch FalconX for it to appear.

This is what FalconX is having issues with, the "toolbars space". If either you move the icons as shown in the bottom gif or when new programs, that you have set to show permanent by the clock, are started up, it'll overlaps/hide the toolbars..

**Comment by ChrisAnd1998** [comment]
I might have finally gotten a fix. I am still testing it though.
https://chrisandriessen.nl/web/img/2019-12-28%2009-51-51.mp4

Test version:
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.7.0_v3.zip

**Comment by Cabola** [comment]
nice!
