### ISSUE TITLE
9 icons on the taskbar makes the icons jitter left to right (Icons continuously moving)

### ISSUE THREAD

**Issue by sorun** [ChrisAnd1998/FalconX-Center-Taskbar#98]

**Comment by Cabola** [comment]
yup same happens to me.

**Comment by ChrisAnd1998** [comment]
What effect do you use?
And what DPI setting do you have?

**Comment by Cabola** [comment]
I use the default setup, and they do stop shifting from side to side after some time tho..

**Comment by ChrisAnd1998** [comment]
Hmm, but still. I hoped i had fixed it but, i will try to reproduce it again.

**Comment by sorun** [comment]
> Hmm, but still. I hoped i had fixed it but, i will try to reproduce it again.

So my install got updated yesterday and since then its been fixed. Didn't see anything in your patch notes so I'm wondering if it fixed itself?

**Comment by ChrisAnd1998** [comment]
@sorun on what version are you currently?

**Comment by wimagee** [comment]
I'm seeing it jitter back and forward horizontally on all versions higher than 1.3.1. Quite a large 43" 4k display but other than that it's a completely standard Win 10 setup. 100% scaling on primary screen - 200% on secondary screen.

**Comment by mihaimpop** [comment]
I found a possible **workaround**.

In Windows 10
1. Go to FalconX.exe Properties
2. Go to 'Compatibility' tab
3. Click 'Change high DPI settings' button
4. Check 'Override high DPI scaling behavior. Scaling Performed by:'
5. From the dropdown select 'Application'
6. Ok, Apply, Ok.

Restart FalconX.

My FalconX settings are: 
- Enable taskbar styling, with 'Blur' mode
- Check 'Run at StartUp'

My Windows taskbar settings are:
- Small taskbar buttons
- Taskbar location on screen: Bottom
- Combine taskbar buttons: Always, hide labels

My FalconX.cfg:
```
BackEaseOut
500
0
True
False
True
2
0
```

**Comment by ChrisAnd1998** [comment]
@mihaimpop Oh wow thanks for finding this out!

I can now do this automatically with:
SetProcessDPIAware()

Here's a testing version.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.5.0_v1.zip

**Comment by wimagee** [comment]
Hi there - unfortunately neither the workaround or the test build seem to make any difference on mine. Strangely it works fine on another PC which uses the same screen - although the second screen on it is different.

**Comment by ChrisAnd1998** [comment]
@wimagee What are your FalconX settings? DPI?

**Comment by Cabola** [comment]
yea didn't do anything for me either, mine still bumps from side to side

**Comment by wimagee** [comment]
@ChrisAnd1998 I'm running on Dell XPS with external display. So two 4K displays (laptop running at 150% scaling - and an external screen (set as primary) running at 100%). I've tried setting both to 100% but doesn't make a difference.

Config is:

`BackEaseOut
500
110
False
False
False
1
0`

Happy to try test builds or get logs etc if can be of any help.

**Comment by Cabola** [comment]
where's the config file located?

**Comment by ChrisAnd1998** [comment]
Thanks for sharing your setting @Cabola & @wimagee.

I have a testing version again
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.5.0_v3.zip

**Comment by Cabola** [comment]
still moves, like 1px, from side do side

**Comment by ChrisAnd1998** [comment]
@Cabola Damn, i even blocked the animator when the change is 5px and lower.

**Comment by Cabola** [comment]
That worked! There's no side to side any more!!

It ran the first loop process then halted till I went into the settings, then it began the loop but still no bouncing! This is how my output looked like before entering settings:
![falconxoutput](https://user-images.githubusercontent.com/19853946/70860176-96efcf80-1f1e-11ea-9bac-9d3cf003363e.png)

When the loop began it just kept saying that "Animation 1 | Aborted difference too small" message and still didn't bounce from side to side!!

**Comment by ChrisAnd1998** [comment]
Very nice :)

I will wait a bit just to be sure XD.
I hope to bring this update out today.

**Comment by wimagee** [comment]
Brilliant! Seems to be working well on both of my machines now. The screen connect / disconnect restart thing is also really beneficial for those of us on laptops with external monitors. Thanks!
